Repository TheAlgorithms/Python, pull requests merged in 2019-11, with the labels that each got.

#1524 Fractional knapsack
  dynamic_programming/fractional_knapsack_2.py
Labels: Need Reviews

#1590 added current stock price
  web_programming/current_stock_price.py
Labels: automated tests are failing

#1594 GitHub Action to mark stale issues and pull requests
  .github/workflows/stale.yml
Labels: Need Reviews

#906 add a generic heap
  data_structures/data_structures/heap/heap_generic.py
Labels: no-pr-activity
