Repository TheAlgorithms/Python, pull requests merged in 2019-08, with the labels that each got.

#639 Create collatz_sequence.py
  maths/collatz_sequence.py
Labels: Need Reviews

#941 Create Quadratic Equations(Complexes Numbers)
  maths/Quadratic Equations(Complexes Numbers)
Labels: automated tests are failing

#1100 Added pytests to hashes/md5.py
  hashes/md5.py
Labels: OK to merge

#1107 Add test for QuadraticEquation()
  maths/quadratic_equations_complex_numbers.py
Labels: OK to merge

#1087 Travis CI: Run each failing pytest in allow_failures mode
  .travis.yml
Labels: OK to merge

#1016 Travis CI: Add pytest --doctest-modules machine_learning
  machine_learning/perceptron.py
  machine_learning/random_forest_classification/random_forest_classification.py
  machine_learning/random_forest_regression/random_forest_regression.py
  neural_network/perceptron.py
  requirements.txt
Labels: Need Reviews

#1121 Fix tests for file_transfer and perceptron.py
  .travis.yml
  file_transfer/ftp_send_receive.py
Labels: OK to merge

#1123 Add type hints to binary_tree_traversals.py
  traversals/binary_tree_traversals.py
Labels: OK to merge

#1125 Add maths/test_prime_check.py
  maths/test_prime_check.py
Labels: Need Reviews

#1126 Add doctests to networking_flow/minimum_cut.py
  networking_flow/minimum_cut.py
Labels: OK to merge

#1130 Remove 'python' from the filename
  linear_algebra/src/polynom-for-points.py
Labels: OK to merge

#1127 Update .gitignore to remove __pycache__/
  .gitignore
Labels: OK to merge

#1138 added doctests for compare_string and is_for_table
  boolean_algebra/quine_mc_cluskey.py
Labels: OK to merge
