Repository TheAlgorithms/Python, pull requests merged in 2019-07, with the labels that each got.

#953 #945 Backtracking Algorithms
  backtracking/n_queens.py
  backtracking/sum_of_subsets.py
  other/n_queens.py
Labels: OK to merge

#1018 Travis CI: Add pytest --doctest-modules graphs
  .travis.yml
  graphs/basic_graphs.py
  graphs/bellman_ford.py
  graphs/dijkstra_2.py
  graphs/graphs_floyd_warshall.py
  graphs/minimum_spanning_tree_kruskal.py
  graphs/minimum_spanning_tree_prims.py
  graphs/multi_hueristic_astar.py
  graphs/scc_kosaraju.py
Labels: Need Reviews

#1028 Travis CI: Add pytest --doctest-modules neural_network
  .travis.yml
  neural_network/perceptron.py
Labels: Need Reviews

#1036 Remove the space: lucas series.py --> lucas_series.py
  maths/lucas_series.py
Labels: Need Reviews

#1045 Use correct function names in nth_fibonacci_using_matrix_exponentiation.py
  matrix/nth_fibonacci_using_matrix_exponentiation.py
Labels: Need Reviews

#1046 Update DIRECTORY.md
  DIRECTORY.md
Labels: Need Reviews

#1052 dijkstra.py: Use r"strings" to fix two pylint warnings
  graphs/dijkstra.py
Labels: Need Reviews

#1020 Travis CI: Add pytest --doctest-modules maths
  .travis.yml
  maths/abs_min.py
  maths/binary_exponentiation.py
  maths/lucas_series.py
  maths/sieve_of_eratosthenes.py
Labels: Need Reviews, OK to merge

#1023 rotate_matrix.py: Add type hints for return values
  matrix/rotate_matrix.py
Labels: Need Reviews

#1038 Travis CI: Add a flake8 test for unused imports
  .travis.yml
  graphs/bfs.py
  maths/volume.py
  other/primelib.py
  project_euler/problem_13/sol1.py
Labels: Need Reviews

#1076 Rewrite build_directory_md.py
  .travis.yml
  DIRECTORY.md
  scripts/build_directory_md.py
Labels: Need Reviews

#1086 Validate Python filenames
  .travis.yml
  machine_learning/naive_bayes.ipynb
  other/food_wastage_analysis_from_1961-2013_fao.ipynb
  scripts/validate_filenames.py
Labels: Need Reviews

#1088 Fix data_structures to pass our Travis CI pytests
  .travis.yml
  data_structures/stacks/balanced_parentheses.py
  data_structures/stacks/infix_to_postfix_conversion.py
Labels: Need Reviews
