Repository TheAlgorithms/Python, pull requests merged in 2019-12, with the labels that each got.

#1226 Improve prim.py
  DIRECTORY.md
  graphs/prim.py
Labels: no-pr-activity

#1243 Pythagoras
  maths/pythagoras.py
Labels: no-pr-activity

#1229 Code for Eulers Totient function
  maths/eulers_totient.py
Labels: no-pr-activity

#1152 add the index calculation class at digital_image_processing and the hamming code algorithm at hashes
  digital_image_processing/index_calculation.py
  hashes/hamming_code.py
Labels: no-pr-activity

#1621 Adding doctests into LDA algorithm
  divide_and_conquer/convex_hull.py
  machine_learning/linear_discriminant_analysis.py
Labels: automated tests are failing

#1482 Fixed issue #1368
  conversions/decimal_to_octal.py
Labels: Tests are needed

#1216 digital_image_processing/convert_to_negative
  digital_image_processing/convert_to_negative.py
  digital_image_processing/test_digital_image_processing.py
Labels: no-pr-activity

#616 Image processing algorithms added
  digital_image_processing/histogram_equalization/histogram_stretch.py
  digital_image_processing/histogram_equalization/image_data/input.jpg
  digital_image_processing/histogram_equalization/output_data/output.jpg
Labels: no-pr-activity

#1622 Remove \r from strings
  machine_learning/sequential_minimum_optimization.py
  requirements.txt
Labels: OK to merge

#1634 Bug Fixed in newton_raphson_method.py
  arithmetic_analysis/newton_raphson.py
  arithmetic_analysis/newton_raphson_method.py
Labels: Changes Requested, automated tests are failing, bug

#1635 file iterating_through_submasks.py for given mask is added in dynamic_programming
  dynamic_programming/iterating_through_submasks.py
Labels: enhancement

#1339 Update binary_search_tree.py
  .travis.yml
  data_structures/binary_tree/binary_search_tree.py
Labels: no-pr-activity

#1413 Stack using double linked list
  data_structures/stacks/stack_using_dll.py
Labels: Tests are needed, no-pr-activity

#1428 Added binary exponentiaion with respect to modulo
  maths/binary_exp_mod.py
  maths/miller_rabin.py
Labels: no-pr-activity

#1342 Update back_propagation_neural_network.py
  neural_network/back_propagation_neural_network.py
Labels: Tests are needed, no-pr-activity
