Repository TheAlgorithms/Python, pull requests merged in 2019-10, with the labels that each got.

#1266 CONTRIBUTING.md: Fix mistake in doctest ;-)
  CONTRIBUTING.md
Labels: Need Reviews

#1333 Adding doctests for sum_of_subset.py
  dynamic_programming/sum_of_subset.py
Labels: OK to merge

#1302 Add Topological Sort
  blockchain/chinese_remainder_theorem.py
  blockchain/diophantine_equation.py
  blockchain/modular_division.py
  graphs/g_topological_sort.py
  machine_learning/k_nearest_neighbours.py
  maths/fibonacci_sequence_recursion.py
  maths/sum_of_arithmetic_series.py
  sorts/stooge_sort.py
Labels: automated tests are failing

#1235 #840 adds polymonial regression program in python
  machine_learning/polymonial_regression.py
Labels: automated tests are failing

#1310 fuzzy operations added
  fuzzy_logic/fuzzy_operations.py
  requirements.txt
Labels: automated tests are failing

#1389 Python program that surfs 3 site at a time
  requirements.txt
  web_programming/crawl_google_results.py
Labels: automated tests are failing

#1384 Create ActivitySelection
  other/activity_selection.py
Labels: Changes Requested

#1399 Double sort (Added with required updates)
  sorts/double_sort.py
Labels: automated tests are failing

#1406 Create autocomplete_using_trie.py
  other/autocomplete_using_trie.py
Labels: automated tests are failing

#1412 add simple improved Sieve Of Eratosthenes Algorithm
  maths/prime_sieve_eratosthenes.py
Labels: automated tests are failing

#1414 Transfer .ipynb files to TheAlgorithms/Jupyter
  machine_learning/dbscan/dbscan.ipynb
  machine_learning/dbscan/dbscan.py
  machine_learning/naive_bayes.ipynb
  machine_learning/random_forest_classification/Social_Network_Ads.csv
  machine_learning/random_forest_classification/random_forest_classification.py
  machine_learning/random_forest_classification/random_forest_classifier.ipynb
  machine_learning/random_forest_regression/Position_Salaries.csv
  machine_learning/random_forest_regression/random_forest_regression.ipynb
  machine_learning/random_forest_regression/random_forest_regression.py
  machine_learning/reuters_one_vs_rest_classifier.ipynb
  neural_network/fully_connected_neural_network.ipynb
Labels: Need Reviews

#1404 Largest subarray sum
  other/largest_subarray_sum.py
  sorts/bogo_bogo_sort.py
  sorts/i_sort.py
Labels: automated tests are failing

#1488 finding max
  maths/find_max.py
Labels: automated tests are failing

#1499 Add Travis_CI_tests_are_failing.md
  Travis_CI_tests_are_failing.md
  images/Travis_CI_fail_1.png
  images/Travis_CI_fail_2.png
Labels: Need Reviews

#871 Page replacement algorithm, LRU
  other/least_recently_used.py
Labels: automated tests are failing

#876 Addition of Secant Method
  arithmetic_analysis/secant_method.py
Labels: automated tests are failing

#1445 Create GAN.py
  neural_network/gan.py
  neural_network/input_data.py
Labels: automated tests are failing

#1518 Add doctests to other/word_patterns.py
  other/word_patterns.py
Labels: Need Reviews

#1493 Factors of a number
  data_structures/heap/binomial_heap.py
  maths/basic_maths.py
  maths/factors.py
  maths/prime_numbers.py
  neural_network/perceptron.py
Labels: automated tests are failing

#1491 average_mode.py
  maths/average_mode.py
Labels: Tests are needed, automated tests are failing

#1382 Simplified DES
  ciphers/diffie.py
  other/sdes.py
Labels: Tests are needed

#1523 Update quick_select.py
  searches/quick_select.py
Labels: Changes Requested

#1440 Added Problem 33
  project_euler/problem_33/__init__.py
  project_euler/problem_33/sol1.py
Labels: Tests are needed
