Repository TheAlgorithms/Python, pull requests merged in 2020-12, with the labels that each got.

#2682 Chore: Added type hints to searches/binary_search.py
  searches/binary_search.py
Labels: Status: awaiting reviews, Type: enhancement, hacktoberfest-accepted

#3860 Update caesar_cipher.py
  ciphers/caesar_cipher.py
Labels: Type: enhancement

#4038 Optimization for shell sort
  sorts/shell_sort.py
Labels: Status: awaiting reviews, Type: enhancement

#4050 add integer to roman function
  conversions/roman_numerals.py
Labels: Status: awaiting reviews, Type: enhancement

#4053 [mypy] Fix type annotations for arithmetic analysis algorithms
  arithmetic_analysis/in_static_equilibrium.py
  arithmetic_analysis/lu_decomposition.py
  arithmetic_analysis/newton_forward_interpolation.py
  arithmetic_analysis/newton_raphson.py
  arithmetic_analysis/secant_method.py
Labels: Type: enhancement

#4055 [mypy] Add/fix type annotations for backtracking algorithms
  backtracking/all_subsequences.py
  backtracking/coloring.py
  backtracking/hamiltonian_cycle.py
  backtracking/knight_tour.py
  backtracking/minimax.py
  backtracking/n_queens_math.py
  backtracking/sudoku.py
Labels: Type: enhancement

#4056 [mypy] Add/Fix type annotations for bit manipulation algorithms
  bit_manipulation/binary_and_operator.py
  bit_manipulation/binary_or_operator.py
  bit_manipulation/binary_xor_operator.py
  bit_manipulation/single_bit_manipulation_operations.py
Labels: Type: enhancement

#4074 [mypy] Add/fix type annotations for scheduling algorithms
  scheduling/first_come_first_served.py
  scheduling/round_robin.py
  scheduling/shortest_job_first.py
Labels: enhancement

#4065 updated area.py
  maths/area.py
Labels: awaiting reviews, enhancement
