Repository TheAlgorithms/Python, pull requests merged in 2020-11, with the labels that each got.

#3343 Added solution to Project Euler problem 301
  project_euler/problem_301/__init__.py
  project_euler/problem_301/sol1.py
Labels: Status: awaiting changes

#3690 kth order statistic divide and conquer algorithm
  divide_and_conquer/kth_order_statistic.py
Labels: hacktoberfest-accepted

#3513 Added a solution for Project Euler Problem 203 "Squarefree Binomial Coefficients"
  project_euler/problem_203/__init__.py
  project_euler/problem_203/sol1.py
Labels: Good first issue, Status: awaiting changes

#3863 Cache pre-commit workflow
  .github/workflows/pre-commit.yml
Labels: Status: awaiting reviews, Type: enhancement

#2944 Add molecular_chemistry.py
  DIRECTORY.md
  conversions/molecular_chemistry.py
Labels: stale

#3691 Peak of unimodal list DNC algorithm
  divide_and_conquer/peak.py
Labels: hacktoberfest-accepted

#3889 Move CI tests from Travis to GitHub
  .github/workflows/build.yml
  .travis.yml
  ciphers/hill_cipher.py
  machine_learning/forecasting/run.py
  web_programming/instagram_crawler.py
Labels: Type: enhancement

#3811 Changed how the Visited nodes are tracked
  graphs/bfs_shortest_path.py
Labels: Status: on hold, hacktoberfest-accepted, question

#2436 Web programming contribution
  web_programming/currency_converter.py
Labels: Require: Tests, stale

#3420 Renamed octal_to_decimal to octal_to_decimal.py
  conversions/octal_to_decimal.py
Labels: Status: awaiting reviews

#3692 A divide and conquer method in finding the maximum difference pair
  divide_and_conquer/max_difference_pair.py
Labels: hacktoberfest-accepted

#3949 Fixes: #3944 authentication error
  web_programming/fetch_github_info.py
  web_programming/test_fetch_github_info.py
Labels: Type: bugfix

#2557 added binary_count_trailing_zeros.py
  bit_manipulation/binary_count_setbits.py
  bit_manipulation/binary_count_trailing_zeros.py
Labels: Status: awaiting reviews, hacktoberfest-accepted

#3979 Update CONTRIBUTING.md with pre-commit plugin instructions
  CONTRIBUTING.md
Labels: Status: awaiting reviews, Type: documentation

#3970 Fixed LGTM and typehint
  DIRECTORY.md
  maths/lucas_series.py
Labels: Status: awaiting reviews

#3981 Instagram Video and IGTV downloader
  web_programming/instagram_video.py
Labels: Require: Tests

#3070 Hacktoberfest 2020: Conway's Game of Life
  cellular_automata/conways_game_of_life.py
Labels: Require: Tests, Require: Type hints, hacktoberfest-accepted

#2684 Added static typing to backtracking algorithms
  DIRECTORY.md
  backtracking/all_combinations.py
  backtracking/all_permutations.py
  backtracking/n_queens.py
  backtracking/rat_in_maze.py
  backtracking/sum_of_subsets.py
Labels: Require: Descriptive names, Require: Tests, hacktoberfest-accepted

#3149 Add typehints to blockchain
  blockchain/chinese_remainder_theorem.py
  blockchain/diophantine_equation.py
  blockchain/modular_division.py
Labels: Require: Descriptive names

#3987 Fix mypy in #2684
  backtracking/all_combinations.py
  backtracking/all_permutations.py
  backtracking/n_queens.py
  backtracking/rat_in_maze.py
  backtracking/sum_of_subsets.py
Labels: Require: Descriptive names, Require: Tests

#3977 Validate only submitted Project Euler solution
  .github/workflows/build.yml
  .github/workflows/project_euler.yml
  scripts/validate_solutions.py
Labels: Status: awaiting reviews

#3988 Fix mypy in #3149
  blockchain/chinese_remainder_theorem.py
  blockchain/diophantine_equation.py
  blockchain/modular_division.py
Labels: Status: awaiting reviews

#3976 Electric power
  electronics/electric_power.py
Labels: Status: awaiting reviews
