Repository TheAlgorithms/Python, pull requests merged in 2020-10, with the labels that each got.

#2524 Update area.py
  maths/area.py
Labels: hacktoberfest-accepted

#2765 Fix pre-commit error in GitHub action file
  .github/workflows/auto_close_empty_issues.yml
Labels: Need Reviews

#2891 Hacktoberfest 2020: Add typehints and default argument for project_euler/problem_01
  project_euler/problem_01/sol1.py
  project_euler/problem_01/sol2.py
  project_euler/problem_01/sol3.py
  project_euler/problem_01/sol4.py
  project_euler/problem_01/sol5.py
  project_euler/problem_01/sol6.py
  project_euler/problem_01/sol7.py
Labels: hacktoberfest-accepted

#2896 bring problem_30 solution in line with project style guidelines
  project_euler/problem_30/sol1.py
Labels: hacktoberfest-accepted

#2887 Hactoberfest - Added a solution to Project Euler 120
  project_euler/problem_120/__init__.py
  project_euler/problem_120/sol1.py
Labels: hacktoberfest-accepted

#2898 Hacktoberfest 2020: Add default args, typehints, expand variable names, and fix solutions for PE prob 02
  project_euler/problem_02/sol1.py
  project_euler/problem_02/sol2.py
  project_euler/problem_02/sol3.py
  project_euler/problem_02/sol4.py
  project_euler/problem_02/sol5.py
Labels: hacktoberfest-accepted

#2882 Add type hints for "strings" folder
  DIRECTORY.md
  strings/aho_corasick.py
  strings/boyer_moore_search.py
  strings/knuth_morris_pratt.py
  strings/levenshtein_distance.py
  strings/manacher.py
  strings/rabin_karp.py
Labels: Changes Requested

#2924 Project Euler Problem 10: style improvements
  project_euler/problem_10/sol1.py
  project_euler/problem_10/sol2.py
  project_euler/problem_10/sol3.py
Labels: hacktoberfest-accepted

#2917 Hacktoberfest 2020: Add style improvements for Project Euler Problem 03
  project_euler/problem_03/sol1.py
  project_euler/problem_03/sol2.py
  project_euler/problem_03/sol3.py
Labels: Changes Requested, hacktoberfest-accepted

#2901 Hacktoberfest 2020 - Add typehints and default input for project_euler/problem_25
  project_euler/problem_25/sol1.py
  project_euler/problem_25/sol2.py
  project_euler/problem_25/sol3.py
Labels: Changes Requested, hacktoberfest-accepted

#2957 Add default arguments for Project Euler problem 6
  project_euler/problem_06/sol1.py
  project_euler/problem_06/sol2.py
  project_euler/problem_06/sol3.py
  project_euler/problem_06/sol4.py
  project_euler/problem_06/test_solutions.py
Labels: hacktoberfest-accepted

#2945 Hacktoberfest 2020: Add style improvements to solutions for Project Euler Problem 04
  project_euler/problem_04/sol1.py
  project_euler/problem_04/sol2.py
Labels: hacktoberfest-accepted

#2962 Add default args and type hints for Project Euler problem 20
  project_euler/problem_20/sol1.py
  project_euler/problem_20/sol2.py
  project_euler/problem_20/sol3.py
  project_euler/problem_20/sol4.py
Labels: Need Reviews

#2976 Update code style for Project Euler Problem 28
  project_euler/problem_28/sol1.py
Labels: hacktoberfest-accepted

#2958 Hacktoberfest 2020 - Style Improvements for project_euler/problem_26
  project_euler/problem_26/sol1.py
Labels: hacktoberfest-accepted

#2659 Fix: Multiple errors in fibonacci search.
  searches/fibonacci_search.py
Labels: Changes Requested

#2973 Add default args and type hints for Project Euler problem 7
  project_euler/problem_07/sol1.py
  project_euler/problem_07/sol2.py
  project_euler/problem_07/sol3.py
Labels: Need Reviews

#2992 [Project Euler] Fix code style in Problem 41
  project_euler/problem_41/sol1.py
Labels: Changes Requested

#3023 Hacktoberfest 2020 - coding style for project_euler problem 39
  project_euler/problem_39/sol1.py
Labels: hacktoberfest-accepted

#3047 [Project Euler] Added type hints and refactored the code a bit for Problem 14
  project_euler/problem_14/sol1.py
  project_euler/problem_14/sol2.py
Labels: Changes Requested

#3062 Hacktoberfest 2020 - coding style changes for project_euler problem 36 and 35
  project_euler/problem_35/sol1.py
  project_euler/problem_36/sol1.py
Labels: hacktoberfest-accepted

#3065 Created max_sum_sliding_window in Python/other
  other/max_sum_sliding_window.py
Labels: Need Reviews

#2900 Cleanup Project Euler Problem 01
  project_euler/problem_01/sol1.py
  project_euler/problem_01/sol2.py
  project_euler/problem_01/sol3.py
  project_euler/problem_01/sol4.py
  project_euler/problem_01/sol5.py
  project_euler/problem_01/sol6.py
  project_euler/problem_01/sol7.py
Labels: hacktoberfest-accepted

#2742 feat: added prim's algorithm v2
  DIRECTORY.md
  graphs/minimum_spanning_tree_prims2.py
Labels: hacktoberfest-accepted

#2885 Project Euler Problem 80
  DIRECTORY.md
  project_euler/problem_80/__init__.py
  project_euler/problem_80/sol1.py
Labels: Changes Requested

#3094 [Project Euler] Fix code style for multiple problems
  project_euler/problem_13/sol1.py
  project_euler/problem_17/sol1.py
  project_euler/problem_21/sol1.py
  project_euler/problem_31/sol1.py
  project_euler/problem_31/sol2.py
  project_euler/problem_33/sol1.py
  project_euler/problem_43/sol1.py
  project_euler/problem_44/sol1.py
  project_euler/problem_46/sol1.py
  project_euler/problem_551/sol1.py
  project_euler/problem_63/sol1.py
Labels: Need Reviews

#2931 Added solution for Project Euler problem 119
  project_euler/problem_119/__init__.py
  project_euler/problem_119/sol1.py
Labels: Changes Requested, Tests are needed

#2875 Add solution for Project Euler problem 191
  project_euler/problem_191/__init__.py
  project_euler/problem_191/sol1.py
Labels: Changes Requested

#3177 Fixes: #3163 - Add new solution for problem 234
  project_euler/problem_234/sol1.py
Labels: Changes Requested

#2934 Added solution to Project Euler 69
  project_euler/problem_69/__init__.py
  project_euler/problem_69/sol1.py
Labels: Changes Requested, hacktoberfest-accepted

#2940 Hacktoberfest - Added a solution to Project Euler 72
  project_euler/problem_72/__init__.py
  project_euler/problem_72/sol1.py
Labels: Changes Requested, hacktoberfest-accepted

#3018 Hacktoberfest: Add project euler problem 51
  project_euler/problem_51/__init__.py
  project_euler/problem_51/sol1.py
Labels: Changes Requested, hacktoberfest-accepted

#3344 BROKEN BUILD: Fix a failing precommit test
  DIRECTORY.md
  graphs/tests/test_min_spanning_tree_prim.py
Labels: enhancement

#3264 Add typehints ciphers and bool alg
  boolean_algebra/quine_mc_cluskey.py
  ciphers/affine_cipher.py
  ciphers/base64_cipher.py
  ciphers/brute_force_caesar_cipher.py
  ciphers/cryptomath_module.py
  ciphers/decrypt_caesar_with_chi_squared.py
  ciphers/deterministic_miller_rabin.py
  ciphers/diffie.py
  ciphers/elgamal_key_generator.py
  ciphers/hill_cipher.py
  ciphers/mixed_keyword_cypher.py
  ciphers/morse_code_implementation.py
  ciphers/onepad_cipher.py
  ciphers/playfair_cipher.py
  ciphers/porta_cipher.py
  ciphers/rabin_miller.py
  ciphers/rot13.py
  ciphers/rsa_cipher.py
  ciphers/rsa_factorization.py
  ciphers/rsa_key_generator.py
  ciphers/simple_substitution_cipher.py
  ciphers/trafid_cipher.py
  ciphers/transposition_cipher.py
  ciphers/vigenere_cipher.py
  ciphers/xor_cipher.py
Labels: OK to merge, hacktoberfest-accepted

#3122 Added solution for Project Euler problem 72
  project_euler/problem_072/sol2.py
Labels: Changes Requested

#3129 Added solution for Project Euler problem 75.
  project_euler/problem_075/__init__.py
  project_euler/problem_075/sol1.py
Labels: Changes Requested

#3380 New doubly linkedlist PR: pull/2573
  data_structures/linked_list/doubly_linked_list_two.py
Labels: hacktoberfest-accepted

#2946 Hacktoberfest 2020: Added computer vision algorithm
  computer_vision/meanthreshold.py
Labels: hacktoberfest-accepted

#3259 Project Euler 57 - Square root convergents
  project_euler/problem_057/__init__.py
  project_euler/problem_057/sol1.py
Labels: Changes Requested

#2598 Adding in the evaluate postfix notation using Stack
  data_structures/stacks/evaluate_postfix_notations.py
Labels: automated tests are failing

#3378 Create GitHub action only for Project Euler
  .github/workflows/project_euler.yml
  .travis.yml
Labels: Need Reviews, enhancement

#3410 Create .gitattributes for Cross OS compatibility
  .gitattributes
Labels: hacktoberfest-accepted

#3518 Replace main with __main__
  web_programming/slack_message.py
Labels: hacktoberfest-accepted

#2743 Add a naive recursive implementation of 0-1 Knapsack Problem
  knapsack/README.md
  knapsack/__init__.py
  knapsack/knapsack.py
  knapsack/test_knapsack.py
Labels: hacktoberfest-accepted

#3554 Median of Two Arrays
  other/median_of_two_arrays.py
Labels: hacktoberfest-accepted

#3616 Pyupgrade to python3.8
  DIRECTORY.md
  ciphers/simple_substitution_cipher.py
  ciphers/xor_cipher.py
  compression/lempel_ziv.py
  compression/lempel_ziv_decompress.py
  data_structures/binary_tree/segment_tree_other.py
  data_structures/heap/heap.py
  data_structures/linked_list/deque_doubly.py
  graphs/minimum_spanning_tree_boruvka.py
  machine_learning/astar.py
  machine_learning/k_means_clust.py
  maths/entropy.py
  maths/numerical_integration.py
  project_euler/problem_013/sol1.py
  project_euler/problem_018/solution.py
  project_euler/problem_042/solution42.py
  project_euler/problem_049/sol1.py
  project_euler/problem_054/sol1.py
  project_euler/problem_054/test_poker_hand.py
  project_euler/problem_063/sol1.py
  project_euler/problem_067/sol1.py
Labels: Need Reviews

#3704 Move validate_solutions and add durations flag to pytest.ini
  .github/workflows/autoblack.yml
  .github/workflows/codespell.yml
  .github/workflows/project_euler.yml
  .travis.yml
  pytest.ini
  scripts/project_euler_answers.json
  scripts/validate_solutions.py
Labels: Need Reviews, enhancement

#3242 Fix style of the first ten solutions for Project Euler
  project_euler/problem_001/sol1.py
  project_euler/problem_001/sol2.py
  project_euler/problem_001/sol3.py
  project_euler/problem_001/sol4.py
  project_euler/problem_001/sol5.py
  project_euler/problem_001/sol6.py
  project_euler/problem_001/sol7.py
  project_euler/problem_002/sol1.py
  project_euler/problem_002/sol2.py
  project_euler/problem_002/sol3.py
  project_euler/problem_002/sol4.py
  project_euler/problem_002/sol5.py
  project_euler/problem_003/sol1.py
  project_euler/problem_003/sol2.py
  project_euler/problem_003/sol3.py
  project_euler/problem_004/sol1.py
  project_euler/problem_004/sol2.py
  project_euler/problem_005/sol1.py
  project_euler/problem_005/sol2.py
  project_euler/problem_006/sol1.py
  project_euler/problem_006/sol2.py
  project_euler/problem_006/sol3.py
  project_euler/problem_006/sol4.py
  project_euler/problem_007/sol1.py
  project_euler/problem_007/sol2.py
  project_euler/problem_007/sol3.py
  project_euler/problem_008/sol1.py
  project_euler/problem_008/sol2.py
  project_euler/problem_008/sol3.py
  project_euler/problem_009/sol1.py
  project_euler/problem_009/sol2.py
  project_euler/problem_009/sol3.py
  project_euler/problem_010/sol1.py
  project_euler/problem_010/sol2.py
  project_euler/problem_010/sol3.py
Labels: Changes Requested, enhancement

#3756 fixes: #2969
  .github/stale.yml
Labels: hacktoberfest, hacktoberfest-accepted

#2916 Implement the melkman anlgorithm for computing convex hulls
  divide_and_conquer/convex_hull.py
Labels: hacktoberfest-accepted

#3522 Add first solution for Project Euler Problem 207
  DIRECTORY.md
  project_euler/problem_207/__init__.py
  project_euler/problem_207/sol1.py
Labels: Status: awaiting changes

#3700 Added decimal_isolate.py
  maths/decimal_isolate.py
Labels: hacktoberfest, hacktoberfest-accepted
