Repository TheAlgorithms/Python, pull requests merged in 2020-01, with the labels that each got.

#1353 update volumes with type hints + some refactoring
  maths/volume.py
Labels: no-pr-activity

#1675 Add a program to evaluate a string in prefix notation (Polish Notation)
  DIRECTORY.md
  data_structures/stacks/prefix_evaluation.py
Labels: OK to merge

#1683 A recursive insertion sort
  sorts/recursive_insertion_sort.py
Labels: Changes Requested, Tests are needed, enhancement

#1660 enhance swapping code in link
  data_structures/linked_list/swap_nodes.py
Labels: Changes Requested, Tests are needed

#1717 Mandates referencing issue in PR
  .github/pull_request_template.md
  CONTRIBUTING.md
Labels: Need Reviews, enhancement

#1719 Augment binary search algorithms
  searches/binary_search.py
Labels: enhancement
