Repository TheAlgorithms/Python, pull requests merged in 2020-05, with the labels that each got.

#1925 Wrap lines that go beyond GiHub Editor
  .travis.yml
  DIRECTORY.md
  ciphers/rsa_cipher.py
  ciphers/rsa_key_generator.py
  data_structures/linked_list/doubly_linked_list.py
  divide_and_conquer/strassen_matrix_multiplication.py
  dynamic_programming/bitmask.py
  dynamic_programming/edit_distance.py
  machine_learning/decision_tree.py
  machine_learning/logistic_regression.py
  machine_learning/support_vector_machines.py
  maths/pi_monte_carlo_estimation.py
  maths/zellers_congruence.py
  matrix/matrix_class.py
  other/password_generator.py
  other/sierpinski_triangle.py
  project_euler/problem_99/sol1.py
  searches/binary_search.py
  web_programming/slack_message.py
Labels: Need Reviews

#1876 Create sol2.py
  DIRECTORY.md
  project_euler/problem_31/sol2.py
Labels: OK to merge

#1908 Added Lstm example for stock predection
  machine_learning/lstm/lstm_prediction.py
  machine_learning/lstm/sample_data.csv
  requirements.txt
Labels: automated tests are failing

#1866 Add graphs/frequent_pattern_graph_miner.py
  graphs/frequent_pattern_graph_miner.py
Labels: automated tests are failing

#1996 Pi digit extraction algorithm
  DIRECTORY.md
  maths/bailey_borwein_plouffe.py
Labels: automated tests are failing

#2002 consists of area of various geometrical shapes
  maths/area.py
Labels: automated tests are failing

#2013 Precision must be a nonnegative integer
  data_structures/linked_list/singly_linked_list.py
  maths/bailey_borwein_plouffe.py
Labels: Need Reviews
