Repository TheAlgorithms/Python, pull requests merged in 2020-02, with the labels that each got.

#1722 Added first come first served scheduling
  scheduling/first_come_first_served.py
Labels: Changes Requested, enhancement

#1734 Travis CI: Don’t allow bare exceptions
  .travis.yml
  ciphers/transposition_cipher.py
  ciphers/xor_cipher.py
  hashes/hamming_code.py
  linear_algebra/src/test_linear_algebra.py
Labels: automated tests are failing

#1742 Fixes black failures
  maths/montecarlo.py
  scheduling/first_come_first_served.py
Labels: automated tests are failing

#1745 Fixes LGTM issues
  dynamic_programming/max_sum_contiguous_subsequence.py
  searches/hill_climbing.py
Labels: Need Reviews, bug, enhancement

#1739 Added Bisection algorithm
  maths/bisection.py
Labels: enhancement

#1746 Fixes unused variable errors in LGTM
  ciphers/mixed_keyword_cypher.py
  data_structures/binary_tree/binary_search_tree.py
  graphs/a_star.py
  hashes/hamming_code.py
  linear_algebra/src/polynom-for-points.py
  matrix/matrix_operation.py
Labels: Need Reviews

#1751 Fixes black failures from Previous PR
  data_structures/binary_tree/binary_search_tree.py
  dynamic_programming/optimal_binary_search_tree.py
  hashes/hamming_code.py
  maths/bisection.py
  searches/tabu_search.py
  strings/aho-corasick.py
Labels: Need Reviews, on hold

#1784 extend estimation of area under curve of y=x using monte carlo simulation to any given lower and upper bound
  maths/monte_carlo.py
Labels: enhancement
