Repository TheAlgorithms/Python, pull requests merged in 2020-04, with the labels that each got.

#1834 Create Python/quantum/README.md
  quantum/README.md
  strings/reverse_words.py
Labels: OK to merge

#1885 CONTRIBUTING.md: What is an Algorithm?
  CONTRIBUTING.md
  DIRECTORY.md
Labels: Need Reviews

#1872 Initialize set with source in DFS
  DIRECTORY.md
  graphs/depth_first_search.py
  graphs/depth_first_search_2.py
  graphs/dfs.py
Labels: OK to merge

#1754 Create is_palindrome.py
  strings/is_palindrome.py
Labels: no-pr-activity

#1911 Blacken one_dimensional.py
  .travis.yml
  DIRECTORY.md
  cellular_automata/one_dimensional.py
Labels: Need Reviews
