Repository TheAlgorithms/Python, pull requests merged in 2021-02, with the labels that each got.

#4172 [mypy] Add/fix type annotations for boolean_algebra
  boolean_algebra/quine_mc_cluskey.py
Labels: enhancement

#4085 [mypy] Add/fix type annotations for binary trees in data structures
  data_structures/binary_tree/binary_search_tree_recursive.py
  data_structures/binary_tree/lazy_segment_tree.py
  data_structures/binary_tree/treap.py
Labels: enhancement

#3865 Create slowsort.py
  sorts/slowsort.py
Labels: awaiting reviews

#4195 add count_number_of_one_bits.py
  bit_manipulation/count_number_of_one_bits.py
Labels: awaiting reviews

#3875 Quick sort with lomuto partition
  sorts/quick_sort_3_partition.py
Labels: enhancement

#4210 Update License Year
  LICENSE.md
Labels: awaiting reviews, documentation

#4207 Implementation of the algorithm for the Koch snowflake
  graphics/koch_snowflake.py
Labels: require tests

#4215 [mypy] Add/fix type annotations for quick_sort(#4085)
  sorts/quick_sort.py
Labels: enhancement

#4216 [mypy] Add/fix type annotations for cellular automata
  cellular_automata/conways_game_of_life.py
  cellular_automata/one_dimensional.py
Labels: awaiting reviews, enhancement

#4214 [mypy] Add/fix type annotations for avl tree in data structures
  data_structures/binary_tree/avl_tree.py
Labels: enhancement

#4118 Changes occurences of str.format to f-strings
  ciphers/rsa_cipher.py
  ciphers/rsa_key_generator.py
  compression/burrows_wheeler.py
  data_structures/binary_tree/non_recursive_segment_tree.py
  data_structures/binary_tree/red_black_tree.py
  data_structures/linked_list/deque_doubly.py
  dynamic_programming/climbing_stairs.py
  dynamic_programming/iterating_through_submasks.py
  machine_learning/knn_sklearn.py
  maths/3n_plus_1.py
  maths/quadratic_equations_complex_numbers.py
  matrix/nth_fibonacci_using_matrix_exponentiation.py
  matrix/sherman_morrison.py
  strings/levenshtein_distance.py
Labels: enhancement

#4224 [mypy]Correction of all errors in the sorts directory
  sorts/bucket_sort.py
  sorts/cocktail_shaker_sort.py
  sorts/patience_sort.py
  sorts/radix_sort.py
  sorts/recursive_insertion_sort.py
Labels: awaiting reviews, enhancement

#4220 [mypy] Added/fixed type annotations for "graphics\bezier_curve.py"
  graphics/bezier_curve.py
Labels: enhancement

#4232 Add mandelbrot algorithm
  graphics/mandelbrot.py
Labels: require descriptive names

#4221 [mypy] Added/fixed type annotations for "rotate_matrix.py" & "test_matrix_operation.py"
  matrix/rotate_matrix.py
  matrix/tests/test_matrix_operation.py
Labels: awaiting reviews, enhancement
