Repository TheAlgorithms/Python, pull requests merged in 2021-10, with the labels that each got.

#4857 Fix grammar of comments in backtracking/coloring.py
  backtracking/coloring.py
Labels: enhancement, hacktoberfest-accepted

#4869 Correct grammar in backtracking/n_queens_math.py
  backtracking/n_queens_math.py
Labels: enhancement

#4868 Correct grammar in hamiltonian_cycle.py
  backtracking/hamiltonian_cycle.py
Labels: enhancement

#4972 fix: comment
  sorts/patience_sort.py
Labels: enhancement, hacktoberfest-accepted

#4928 Fix word typos in comments
  sorts/bead_sort.py
  sorts/odd_even_transposition_single_threaded.py
  sorts/topological_sort.py
  strings/prefix_function.py
Labels: enhancement

#4844 bugfix: Add abs_max.py & abs_min.py empty list detection
  maths/abs_max.py
  maths/abs_min.py
Labels: enhancement

#4808 Improve Project Euler problem 112 solution 1
  project_euler/problem_112/sol1.py
Labels: enhancement

#5388 Update queue implementation
  graphs/breadth_first_search.py
  graphs/breadth_first_search_2.py
  graphs/check_bipartite_graph_bfs.py
Labels: enhancement

#5166 Improve Project Euler problem 070 solution 1
  project_euler/problem_070/sol1.py
Labels: enhancement

#5652 [mypy] Fix type annotations in `data_structures/binary_tree/non_recursive_segment_tree.py`
  data_structures/binary_tree/non_recursive_segment_tree.py
Labels: enhancement

#5635 Fixed grammatical errors in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#5634 [mypy] Add/fix type annotations in `data_structures/heap/skew_heap.py`
  data_structures/heap/skew_heap.py
Labels: enhancement

#5710 Credit Card Validator: Fix spellings
  strings/credit_card_validator.py
Labels: enhancement

#5708 Improve Project Euler problem 078 solution 1
  project_euler/problem_078/sol1.py
Labels: enhancement

#5705 Improve Project Euler problem 072 solution 1
  project_euler/problem_072/sol1.py
Labels: enhancement

#5703 Improve Project Euler problem 092 solution 1
  project_euler/problem_092/sol1.py
Labels: enhancement

#4806 Improve checking anagrams in O(n) with dictionary
  strings/check_anagrams.py
Labels: enhancement

#5379 Make decrypt_caesar_with_chi_squared work with upper case letters
  ciphers/decrypt_caesar_with_chi_squared.py
Labels: enhancement

#5704 [mypy] Fix type annotations in `data_structures/heap/randomized_heap.py`
  data_structures/heap/randomized_heap.py
Labels: enhancement

#5615 Local Weighted Learning
  machine_learning/local_weighted_learning/__init__.py
  machine_learning/local_weighted_learning/local_weighted_learning.md
  machine_learning/local_weighted_learning/local_weighted_learning.py
Labels: awaiting reviews, documentation

#5658 Deduplicate euclidean_length method in Vector
  linear_algebra/src/lib.py
  linear_algebra/src/test_linear_algebra.py
Labels: enhancement

#5677 Rewrote fibonacci.py (#5665)
  dynamic_programming/fibonacci.py
Labels: enhancement

#5576 [mypy] Fix type annotations for linked_stack.py
  DIRECTORY.md
  data_structures/stacks/stack_with_doubly_linked_list.py
  data_structures/stacks/stack_with_singly_linked_list.py
Labels: enhancement

#5725 Fix build issues due to count
  strings/check_anagrams.py
Labels: enhancement
