Repository TheAlgorithms/Python, pull requests merged in 2021-11, with the labels that each got.

#5738 Merge maths/fibonacci.py and maths/fibonacci_sequence_recursion.py
  maths/fibonacci.py
  maths/fibonacci_sequence_recursion.py
Labels: enhancement

#5731 Improve Project Euler problem 012 solution 1
  project_euler/problem_012/sol1.py
Labels: enhancement

#5734 Rewrite maths/fibonacci.py
  maths/fibonacci.py
Labels: enhancement, awaiting reviews

#5742 Fix comment
  DIRECTORY.md
  web_programming/search_books_by_isbn.py
Labels: enhancement

#5730 Add stone unit of measuring weight
  conversions/weight_conversion.py
Labels: enhancement, tests are failing

#5750 Typo
  web_programming/search_books_by_isbn.py
Labels: enhancement

#5289 Add gabor filter
  digital_image_processing/filters/gabor_filter.py
Labels: hacktoberfest-accepted

#5749 [mypy] fix type annotations in `data_structures/queue/circular_queue_linked_list.py`
  data_structures/queue/circular_queue_linked_list.py
Labels: enhancement, awaiting reviews

#5746 Split base85.py into functions, Add doctests
  ciphers/base16.py
  ciphers/base64.py
  ciphers/base85.py
Labels: enhancement

#5745 Uncomment doctest in Project Euler problem 009 solution 3
  project_euler/problem_009/sol3.py
Labels: enhancement

#5753 Fixed typo for codespell
  project_euler/problem_045/sol1.py
  web_programming/get_user_tweets.py
Labels: enhancement

#5751 Replace Travis CI mentions with GitHub actions
  CONTRIBUTING.md
  project_euler/README.md
  project_euler/problem_012/sol2.py
Labels: documentation

#5759 [mypy] Fixes typing errors in other/dpll
  other/davisb_putnamb_logemannb_loveland.py
Labels: enhancement

#5757 [mypy] Fix type annotations in `data_structures/binary_tree/lowest_common_ancestor.py`
  data_structures/binary_tree/lowest_common_ancestor.py
Labels: enhancement

#5474 Added newtons_second_law_of_motion.py
  physics/newtons_second_law_of_motion.py
Labels: awaiting reviews

#5754 Add README files 1/7
  arithmetic_analysis/README.md
  audio_filters/README.md
  backtracking/README.md
  bit_manipulation/README.md
  boolean_algebra/README.md
Labels: documentation

#5626 Add all_construct dynamic programming implementation
  dynamic_programming/all_construct.py
Labels: tests are failing

#5698 Added reddit.py to get data from reddit
  web_programming/reddit.py
Labels: tests are failing

#5747 Improve Project Euler problem 014 solution 1
  project_euler/problem_014/sol1.py
Labels: enhancement

#5739 [mypy] Fix type annotations in `data_structures/binary_tree/red_black_tree.py`
  data_structures/binary_tree/red_black_tree.py
Labels: enhancement

#5744 Improve Project Euler problem 014 solution 2
  fuzzy_logic/fuzzy_operations.py
  project_euler/problem_014/sol2.py
  requirements.txt
Labels: enhancement, tests are failing

#5560 Added 2 shapes in volume.py
  maths/volume.py
Labels: enhancement

#5765 Fix `graphs/finding_bridges.py` algorithm + doctests
  graphs/finding_bridges.py
Labels: enhancement, awaiting reviews

#5768 fix typo on line 126
  scheduling/shortest_job_first.py
Labels: enhancement

#5773 Improve Project Euler Problem 10 Sol-1
  project_euler/problem_010/sol1.py
Labels: enhancement

#5772 Improve Project Euler problem 043 solution 1
  DIRECTORY.md
  project_euler/problem_043/sol1.py
Labels: enhancement

#5763 [mypy] Fix type annotations in `data_structures/stacks/next_greater_element.py`
  data_structures/stacks/next_greater_element.py
Labels: enhancement

#5608 mypy: Exclude only 20 files that are still failing
  .github/workflows/build.yml
  mypy.ini
Labels: enhancement

#5789 [mypy] Fix `other/fischer_yates_shuffle.py`
  mypy.ini
  other/fischer_yates_shuffle.py
Labels: enhancement, awaiting reviews

#5782 [mypy] Fix type annotations for maths directory
  maths/average_mode.py
  maths/gamma_recursive.py
  maths/proth_number.py
  maths/series/geometric_series.py
  maths/series/p_series.py
  mypy.ini
Labels: enhancement

#5794 [mypy] Fix type annotations in `graphs/boruvka.py`
  DIRECTORY.md
  graphs/boruvka.py
  mypy.ini
Labels: enhancement

#5795 [mypy] Type annotations for `graphs/finding_bridges.py` and `graphs/random_graph_generator.py`
  graphs/finding_bridges.py
  graphs/random_graph_generator.py
  mypy.ini
Labels: enhancement

#5770 edited strings/anagram.py
  strings/anagrams.py
  strings/anagrams.txt
Labels: enhancement

#5798 [mypy] Type annotations for graphs directory
  graphs/breadth_first_search.py
  graphs/breadth_first_search_2.py
  graphs/check_cycle.py
  graphs/greedy_min_vertex_cover.py
  mypy.ini
Labels: enhancement, tests are failing

#5799 [mypy] Type annotations for searches directory
  mypy.ini
  searches/simulated_annealing.py
  searches/ternary_search.py
Labels: enhancement, tests are failing

#5808 [mypy] Fix `matrix_operation.py`
  DIRECTORY.md
  matrix/matrix_operation.py
  mypy.ini
Labels: enhancement

#5811 [mypy] fix type annotations for other/least-recently-used.py
  other/least_recently_used.py
Labels: enhancement, awaiting reviews

#5755 [mypy] Annotate other/lru_cache and other/lfu_cache
  mypy.ini
  other/lfu_cache.py
  other/lru_cache.py
Labels: enhancement

#5766 add README files 2/8
  cellular_automata/README.md
  ciphers/README.md
  compression/README.md
  computer_vision/README.md
  conversions/README.md
Labels: documentation

#5829 Replace typing.optional with new annotations syntax
  DIRECTORY.md
  data_structures/linked_list/__init__.py
  data_structures/linked_list/circular_linked_list.py
  data_structures/linked_list/has_loop.py
  data_structures/linked_list/middle_element_of_linked_list.py
  maths/pollard_rho.py
Labels: enhancement

#5845 Lowercase g --> Capital G
  other/password_generator.py
Labels: enhancement, awaiting reviews

#5856 Added memoization function in fibonacci
  maths/fibonacci.py
Labels: enhancement, awaiting reviews
