Repository TheAlgorithms/Python, pull requests merged in 2021-03, with the labels that each got.

#4080 Added solution for Project Euler problem 109
  DIRECTORY.md
  project_euler/problem_109/__init__.py
  project_euler/problem_109/sol1.py
Labels: awaiting reviews

#4243 Add arithmetic_mean.py
  maths/series/arithmetic_mean.py
Labels: awaiting reviews

#4233 [mypy] Added/fixed type annotations for "covid_stats_via_xpath.py"
  web_programming/covid_stats_via_xpath.py
Labels: awaiting reviews, enhancement

#4271 Include mypy instructions in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#4268 GitHub Actions: fast-fail on black formatting issues
  .github/workflows/pre-commit.yml
  DIRECTORY.md
Labels: awaiting reviews, enhancement

#4277 New fractals folder
  fractals/koch_snowflake.py
  fractals/mandelbrot.py
  fractals/sierpinski_triangle.py
Labels: enhancement

#4276 build.yml: Run mypy --ignore-missing-imports
  .github/workflows/build.yml
Labels: enhancement

#4275 Explicit euler rename
  maths/euler_method.py
Labels: enhancement

#3805 Created greedy_coin_change.py file
  DIRECTORY.md
  maths/greedy_coin_change.py
Labels: awaiting reviews

#4236 [mypy] Fix type annotations for cellular_automata
  cellular_automata/conways_game_of_life.py
  cellular_automata/one_dimensional.py
Labels: enhancement

#4283 Move files to strings folder
  .pre-commit-config.yaml
  strings/autocomplete_using_trie.py
  strings/detecting_english_programmatically.py
  strings/dictionary.txt
  strings/frequency_finder.py
  strings/palindrome.py
  strings/word_patterns.py
Labels: enhancement

#4278 fix(mypy): Fix annotations for 13 cipher algorithms
  ciphers/a1z26.py
  ciphers/affine_cipher.py
  ciphers/atbash.py
  ciphers/base32.py
  ciphers/base85.py
  ciphers/beaufort_cipher.py
  ciphers/brute_force_caesar_cipher.py
  ciphers/cryptomath_module.py
  ciphers/decrypt_caesar_with_chi_squared.py
  ciphers/diffie.py
  ciphers/elgamal_key_generator.py
  ciphers/enigma_machine2.py
  ciphers/rsa_key_generator.py
Labels: enhancement

#4286 Move files to various folders
  cellular_automata/game_of_life.py
  graphs/markov_chain.py
Labels: enhancement

#4289 Moved "other/anagrams.py" to the string folder
  .pre-commit-config.yaml
  strings/anagrams.py
  strings/words.txt
Labels: enhancement

#4290 [mypy] fix compression folder
  .github/workflows/build.yml
  DIRECTORY.md
  compression/lempel_ziv.py
  neural_network/2_hidden_layers_neural_network.py
Labels: enhancement

#4293 [mypy] fix small folders 2
  .github/workflows/build.yml
  machine_learning/forecasting/run.py
  machine_learning/k_means_clust.py
  machine_learning/word_frequency_functions.py
  neural_network/perceptron.py
  traversals/binary_tree_traversals.py
Labels: enhancement

#4295 Move: traversals/binary_tree_traversals.py --> searches/binary_tree_traversal.py
  .github/workflows/build.yml
  DIRECTORY.md
  searches/binary_tree_traversal.py
  traversals/__init__.py
Labels: enhancement

#4296 mypy: Use a --exclude list
  .github/workflows/build.yml
Labels: awaiting reviews, enhancement

#4297 [mypy] Fix web_programming directory
  .github/workflows/build.yml
  web_programming/currency_converter.py
  web_programming/emails_from_url.py
Labels: enhancement
