Repository TheAlgorithms/Python, pull requests merged in 2021-08, with the labels that each got.

#4581 Fix mypy errors at mst_kruskal
  graphs/minimum_spanning_tree_kruskal.py
  graphs/tests/test_min_spanning_tree_kruskal.py
Labels: enhancement

#4550 Adding the double factorial algorithm
  maths/double_factorial_recursive.py
Labels: require descriptive names

#4601 Refactor graph initializations at basic_graph.py
  graphs/basic_graphs.py
Labels: enhancement

#4612 Fix multi heuristic astar algo
  graphs/multi_heuristic_astar.py
Labels: enhancement, awaiting reviews

#4611 [mypy] Fix type annotations for strings/naive_string_search.py
  strings/naive_string_search.py
Labels: enhancement

#4613 Fix mypy error at maths
  maths/greedy_coin_change.py
  maths/triplet_sum.py
  maths/two_sum.py
Labels: enhancement

#4622 [mypy] Fix type annotations for graphs
  graphs/frequent_pattern_graph_miner.py
  graphs/markov_chain.py
Labels: enhancement, awaiting reviews

#4617 [mypy] Fix type annotations for maths
  maths/armstrong_numbers.py
  maths/average_median.py
  maths/series/harmonic_series.py
Labels: enhancement

#4599 add date_to_weekday finder method
  other/date_to_weekday.py
Labels: awaiting reviews

#4637 [mypy] Fix type annotations for strings
  strings/can_string_be_rearranged_as_palindrome.py
  strings/levenshtein_distance.py
  strings/word_occurrence.py
  strings/word_patterns.py
Labels: enhancement, awaiting reviews

#4660 boruvka.py: A few simplifications and f-strings
  DIRECTORY.md
  graphs/boruvka.py
Labels: enhancement, awaiting reviews

#4641 [mypy] Fix type annotations for strings
  strings/aho_corasick.py
  strings/manacher.py
  strings/min_cost_string_conversion.py
Labels: enhancement, awaiting reviews

#4673 [fixed] unused variable, standalone running, import doctest module
  matrix/nth_fibonacci_using_matrix_exponentiation.py
  matrix/spiral_print.py
  other/fischer_yates_shuffle.py
Labels: enhancement

#4689 [mypy] Fix type annotations for integer_partition.py
  dynamic_programming/integer_partition.py
Labels: enhancement

#4691 Avoid mutable default arguments
  graphs/eulerian_path_and_circuit_for_undirected_graph.py
  graphs/frequent_pattern_graph_miner.py
  maths/radix2_fft.py
Labels: enhancement

#4699 Approve functions used as default arguments
  other/linear_congruential_generator.py
  quantum/ripple_adder_classic.py
Labels: enhancement, awaiting reviews
