Repository TheAlgorithms/Python, pull requests merged in 2021-07, with the labels that each got.

#4521 Fix mypy errors at bfs_zero_one_shortest_path
  graphs/bfs_zero_one_shortest_path.py
Labels: awaiting reviews, enhancement

#4527 Fix mypy errors at prims_algo_2
  graphs/minimum_spanning_tree_prims2.py
Labels: awaiting reviews, enhancement

#4524 Fixes: #{4052} [mypy] fix mypy error: graph
  graphs/scc_kosaraju.py
Labels: enhancement

#4528 Fix mypy errors at kruskal_2
  graphs/minimum_spanning_tree_kruskal2.py
Labels: awaiting reviews, enhancement

#4531 Fix mypy errors at bidirectional_bfs
  graphs/bidirectional_breadth_first_search.py
Labels: awaiting reviews, enhancement

#4510 Improves readability and processing time
  compression/huffman.py
Labels: enhancement

#4547 fixed #4529
  hashes/sha1.py
Labels: enhancement

#4553 Random anime character info
  web_programming/random_anime_character.py
Labels: require tests

#4556 Fix mypy errors at bidirectional_a_star
  graphs/bidirectional_a_star.py
Labels: enhancement

#4557 Fix mypy errors at graph_list
  graphs/graph_list.py
Labels: awaiting reviews, enhancement

#4558 Fix mypy errors at strongly connected component
  graphs/strongly_connected_components.py
Labels: enhancement

#4501 [Mypy fix] fix secant method
  arithmetic_analysis/secant_method.py
Labels: enhancement, tests are failing

#4568 Fix mypy errors at gale_shapely_bigraph_algo
  graphs/gale_shapley_bigraph.py
Labels: awaiting reviews, enhancement

#4544 [fixed] module 'numpy' is imported with both 'import' and 'import from'
  arithmetic_analysis/lu_decomposition.py
Labels: enhancement

#4572 Fix mypy errors at bfs_shortest_path algo
  graphs/breadth_first_search_shortest_path.py
Labels: awaiting reviews, enhancement

#4575 Fix mypy errors at greedy best first algo
  graphs/greedy_best_first.py
Labels: awaiting reviews, enhancement

#4576 Modified the a_star [dot] py for making readable
  graphs/a_star.py
Labels: enhancement

#4579 Fix mypy errors at even_tree algo
  graphs/even_tree.py
Labels: awaiting reviews, enhancement
