Repository TheAlgorithms/Python, pull requests merged in 2021-09, with the labels that each got.

#4687 [mypy] Fix type annotations for dynamic programming
  dynamic_programming/fractional_knapsack_2.py
  dynamic_programming/knapsack.py
  dynamic_programming/longest_increasing_subsequence.py
Labels: enhancement, awaiting reviews

#4748 Fix typos in Project Euler problem 034 solution 1
  project_euler/problem_034/sol1.py
Labels: enhancement, awaiting reviews

#4760 Double factorial iterative
  maths/double_factorial_iterative.py
Labels: awaiting reviews

#4749 Improve Project Euler problem 009 solution 1
  project_euler/problem_009/sol1.py
Labels: enhancement, awaiting reviews

#4665 Update and rename check_valid_ip_address.py to is_ip_v4_address_valid.py
  DIRECTORY.md
  maths/check_valid_ip_address.py
  maths/is_ip_v4_address_valid.py
Labels: enhancement

#4763 from __future__ import annotations
  DIRECTORY.md
  ciphers/a1z26.py
  ciphers/enigma_machine2.py
  ciphers/trafid_cipher.py
  ciphers/xor_cipher.py
Labels: enhancement

#4752 Improve Project Euler problem 014 solution 2
  project_euler/problem_014/sol2.py
Labels: enhancement

#4779 Fixed #4764
  data_structures/disjoint_set/disjoint_set.py
Labels: enhancement
