Repository TheAlgorithms/Python, pull requests merged in 2021-04, with the labels that each got.

#4304 [mypy] Fix directory arithmetic_analysis
  .github/workflows/build.yml
  .github/workflows/pre-commit.yml
  arithmetic_analysis/gaussian_elimination.py
  arithmetic_analysis/in_static_equilibrium.py
Labels: enhancement

#4305 [mypy] fix hashes folder
  .github/workflows/build.yml
  hashes/adler32.py
  hashes/chaos_machine.py
  hashes/enigma_machine.py
  hashes/sdbm.py
Labels: enhancement

#4309 Remove "redefinition" of dict element in problem 74 on project_euler
  project_euler/problem_074/sol1.py
Labels: enhancement

#4307 Minor improvement in binary_shifts.py
  bit_manipulation/binary_shifts.py
Labels: enhancement

#4308 Minor change to bailey_borwein_plouffe.py
  maths/bailey_borwein_plouffe.py
Labels: enhancement

#4306 fix(mypy): type annotations for cipher algorithms
  .github/workflows/build.yml
  ciphers/diffie_hellman.py
  ciphers/hill_cipher.py
  ciphers/mixed_keyword_cypher.py
  ciphers/mono_alphabetic_ciphers.py
  ciphers/morse_code_implementation.py
  ciphers/onepad_cipher.py
  ciphers/playfair_cipher.py
  ciphers/porta_cipher.py
  ciphers/rail_fence_cipher.py
  ciphers/rot13.py
  ciphers/rsa_cipher.py
  ciphers/rsa_factorization.py
  ciphers/shuffled_shift_cipher.py
  ciphers/simple_keyword_cypher.py
  ciphers/simple_substitution_cipher.py
  ciphers/trafid_cipher.py
  ciphers/transposition_cipher.py
  ciphers/transposition_cipher_encrypt_decrypt_file.py
  ciphers/vigenere_cipher.py
  ciphers/xor_cipher.py
Labels: awaiting reviews, enhancement

#4298 Add algorithm for N-body simulation - retry
  DIRECTORY.md
  physics/n_body_simulation.py
Labels: require tests

#4314 fix(mypy): type annotations for conversions algorithms
  .github/workflows/build.yml
  conversions/binary_to_octal.py
  conversions/decimal_to_binary.py
  conversions/decimal_to_hexadecimal.py
  conversions/decimal_to_octal.py
  conversions/prefix_conversions.py
  conversions/weight_conversion.py
Labels: enhancement

#4317 fix(mypy): type annotations for linear algebra algorithms
  .github/workflows/build.yml
  linear_algebra/src/conjugate_gradient.py
  linear_algebra/src/lib.py
  linear_algebra/src/polynom_for_points.py
  linear_algebra/src/power_iteration.py
  linear_algebra/src/rayleigh_quotient.py
  linear_algebra/src/test_linear_algebra.py
  linear_algebra/src/transformations_2d.py
Labels: awaiting reviews, enhancement

#4315 feat: Add mypy configuration file
  .github/workflows/build.yml
  mypy.ini
Labels: enhancement

#4319 Mypy fix rotation.py
  digital_image_processing/rotation/rotation.py
  mypy.ini
Labels: tests are failing

#4320 Fix mypy scripts
  mypy.ini
  scripts/validate_filenames.py
  scripts/validate_solutions.py
Labels: enhancement

#4326 Fixed typo in docstring
  strings/lower.py
Labels: awaiting reviews, enhancement

#4333 Simplify password_generator()
  other/password_generator.py
Labels: enhancement

#4357 feat: Add Discord badge in `README.md`
  README.md
Labels: documentation, tests are failing

#4336 binary_tree_traversals.py: Simplify with dataclasses
  data_structures/binary_tree/binary_tree_traversals.py
Labels: enhancement

#4359 fix(ci): Update pre-commit hooks and apply new black
  .github/workflows/pre-commit.yml
  .pre-commit-config.yaml
  data_structures/binary_tree/binary_search_tree.py
  data_structures/heap/heap.py
  data_structures/heap/max_heap.py
  data_structures/linked_list/deque_doubly.py
  data_structures/stacks/stack.py
  digital_image_processing/sepia.py
  hashes/md5.py
  machine_learning/linear_discriminant_analysis.py
  machine_learning/linear_regression.py
  maths/monte_carlo_dice.py
  other/least_recently_used.py
Labels: awaiting reviews, enhancement
