Repository TheAlgorithms/Python, pull requests merged in 2021-06, with the labels that each got.

#4455 Add catalan_numbers.py
  dynamic_programming/catalan_numbers.py
Labels: awaiting merge

#4464 Mistake in maths/average_mode.py fixed.
  maths/average_mode.py
Labels: bugfix, enhancement

#4474 Add new algorithm for Armstrong numbers
  maths/armstrong_numbers.py
Labels: enhancement

#4499 Remove redundent function in Backtracking Sudoku
  backtracking/sudoku.py
Labels: awaiting reviews, enhancement

#4488 Add/fix mypy type annotations at BFS, DFS in graphs
  graphs/breadth_first_search.py
  graphs/depth_first_search.py
Labels: awaiting reviews, enhancement

#4453 fix(action): delete approve workflow as it does not work
  .github/workflows/approve_workflow_run.yml
Labels: DO-NOT-MERGE, enhancement

#4507 CONTRIBUTING.md: Write for current Python
  CONTRIBUTING.md
Labels: documentation

#4487 Luhn algorithm
  hashes/luhn.py
Labels: awaiting reviews

#4483 Average median type hint
  maths/average_median.py
Labels: awaiting reviews, enhancement

#4485 Average mean refactor
  maths/average_mean.py
Labels: awaiting reviews, enhancement

#4486 basic_maths input check
  maths/basic_maths.py
Labels: enhancement

#4506 Add doctest and fix mypy type annotation in bellman ford
  graphs/bellman_ford.py
Labels: enhancement

#4512 Fix mypy error and add more doctest on bfs_shortest_path
  graphs/bfs_shortest_path.py
Labels: enhancement
