Repository TheAlgorithms/Python, pull requests merged in 2021-05, with the labels that each got.

#4389 [Fix bug] Fix check_pangram_faster in check_pangram.py
  strings/check_pangram.py
Labels: enhancement

#4409 [mypy] Fix type annotations for linked_stack.py, evaluate_postfix_notations.py, stack.py in data structures
  data_structures/stacks/evaluate_postfix_notations.py
  data_structures/stacks/linked_stack.py
  data_structures/stacks/stack.py
Labels: awaiting reviews, enhancement

#4411 feat(ci): Hash project euler solutions
  scripts/project_euler_answers.json
  scripts/validate_solutions.py
Labels: awaiting reviews, enhancement

#4374 Removed keras dependency from requirements.txt
  requirements.txt
Labels: awaiting reviews, enhancement

#4435 Removes python_version condition on tensorflow
  requirements.txt
Labels: enhancement

#4438 Bit manipulation: get the bit at a given position
  bit_manipulation/single_bit_manipulation_operations.py
Labels: awaiting reviews, enhancement

#4445 fix(action): correct indentation for types key
  .github/workflows/approve_workflow_run.yml
  DIRECTORY.md
Labels: awaiting reviews, enhancement

#4446 fix(action): testing and fixing errors
  .github/workflows/approve_workflow_run.yml
Labels: awaiting reviews, enhancement

#4449 Implemented MSD radix sort algorithm in-place
  sorts/msd_radix_sort.py
Labels: enhancement

#4466 Armstrong number definition fix
  maths/armstrong_numbers.py
Labels: enhancement

#4461 markdown consistency
  CONTRIBUTING.md
Labels: documentation

#4470 Rename harriscorner.py to harris_corner.py
  DIRECTORY.md
  computer_vision/harris_corner.py
  computer_vision/mean_threshold.py
Labels: awaiting reviews, enhancement
