Repository TheAlgorithms/Python, pull requests merged in 2022-11, with the labels that each got.

#7881 refactor(abs): Condense `abs_min` and `abs_max`
  maths/abs.py
  maths/abs_max.py
  maths/abs_min.py
Labels: enhancement

#7936 Is power of two
  bit_manipulation/is_power_of_two.py
Labels: tests are failing

#7932 refactor: Move pascals triange to maths/
  .github/workflows/build.yml
  machine_learning/xgboost_classifier.py
  matrix/pascal_triangle.py
  requirements.txt
Labels: enhancement

#7934 add dp up - down minimum cost for tickets
  dynamic_programming/minimum_tickets_cost.py
Labels: require tests

#7939 refactor: Condense `password` related files in one
  dynamic_programming/minimum_tickets_cost.py
  other/check_strong_password.py
  other/password.py
  requirements.txt
Labels: enhancement

#7949 Flake8: Drop ignore of issue A003
  .flake8
  DIRECTORY.md
  data_structures/binary_tree/fenwick_tree.py
  data_structures/heap/heap.py
  data_structures/linked_list/merge_two_lists.py
  data_structures/queue/double_ended_queue.py
  linear_algebra/src/lib.py
  other/lfu_cache.py
  other/lru_cache.py
Labels: enhancement

#7948 Reduce the complexity of linear_algebra/src/polynom_for_points.py
  .flake8
  linear_algebra/src/polynom_for_points.py
Labels: enhancement

#7953 Reduce the complexity of other/graham_scan.py
  .flake8
  other/graham_scan.py
Labels: enhancement, awaiting reviews

#7959 add prefix sum
  DIRECTORY.md
  data_structures/arrays/prefix_sum.py
Labels: awaiting reviews

#7966 Update 3n_plus_1.py
  maths/3n_plus_1.py
Labels: enhancement, awaiting reviews

#7945 Raise error not string
  boolean_algebra/quine_mc_cluskey.py
  ciphers/shuffled_shift_cipher.py
  computer_vision/harris_corner.py
  data_structures/binary_tree/segment_tree_other.py
  data_structures/binary_tree/wavelet_tree.py
  data_structures/linked_list/doubly_linked_list.py
  data_structures/queue/double_ended_queue.py
  graphs/breadth_first_search_shortest_path.py
  graphs/page_rank.py
  linear_algebra/src/polynom_for_points.py
  maths/monte_carlo_dice.py
  matrix/cramers_rule_2x2.py
  other/password.py
  strings/dna.py
Labels: enhancement

#7898 BB84 QKD algorithm
  quantum/bb84.py
  requirements.txt
Labels: awaiting reviews

#7979 feat: Add pronic number implementation
  maths/pronic_number.py
Labels: awaiting reviews

#7977 atbash.py: Tighten up the benchmarks
  DIRECTORY.md
  ciphers/atbash.py
Labels: enhancement, awaiting reviews

#7975 add distribute coins
  DIRECTORY.md
  data_structures/binary_tree/distribute_coins.py
Labels: awaiting reviews

#7980 algorithm: Twin prime
  maths/twin_prime.py
Labels: awaiting reviews

#7974 Additional intro blockchain doc
  blockchain/README.md
Labels: documentation

#7988 fix: mypy 0.991 issues
  conversions/decimal_to_any.py
  data_structures/linked_list/__init__.py
  matrix/matrix_class.py
Labels: enhancement

#7982 Bi directional dijkstra
  graphs/bi_directional_dijkstra.py
Labels: awaiting reviews

#7994 Fix argument validation for count_1s_brian_kernighan_method
  DIRECTORY.md
  bit_manipulation/count_1s_brian_kernighan_method.py
Labels: enhancement, awaiting reviews

#7993 clean of unnecessary checks, imports, calls
  backtracking/rat_in_maze.py
  boolean_algebra/not_gate.py
  cellular_automata/nagel_schrekenberg.py
  ciphers/mixed_keyword_cypher.py
  compression/huffman.py
  data_structures/heap/min_heap.py
  digital_image_processing/test_digital_image_processing.py
  dynamic_programming/fizz_buzz.py
  dynamic_programming/max_sub_array.py
  graphs/directed_and_undirected_(weighted)_graph.py
  graphs/multi_heuristic_astar.py
  linear_algebra/src/lib.py
  machine_learning/sequential_minimum_optimization.py
  maths/find_min.py
  maths/kadanes.py
  maths/largest_subarray_sum.py
  maths/series/geometric_series.py
  networking_flow/ford_fulkerson.py
  networking_flow/minimum_cut.py
  other/password.py
  project_euler/problem_025/sol1.py
  project_euler/problem_036/sol1.py
  quantum/q_fourier_transform.py
  quantum/q_full_adder.py
  quantum/superdense_coding.py
  sorts/msd_radix_sort.py
  strings/aho_corasick.py
Labels: enhancement, tests are failing

#8005 Add backtrack word search in matrix
  DIRECTORY.md
  backtracking/word_search.py
Labels: awaiting reviews
