Repository TheAlgorithms/Python, pull requests merged in 2022-05, with the labels that each got.

#5453 First commit for add_prefix_conversion
  conversions/prefix_conversions_string.py
Labels: awaiting reviews

#6113 Fix some typos.
  ciphers/shuffled_shift_cipher.py
  data_structures/stacks/dijkstras_two_stack_algorithm.py
  divide_and_conquer/inversions.py
  maths/volume.py
  strings/manacher.py
Labels: enhancement, tests are failing

#6122 fix black at prefix string
  conversions/prefix_conversions_string.py
Labels: enhancement

#6112 Fix some typos in solution 1 of euler 686
  project_euler/problem_686/sol1.py
Labels: enhancement, awaiting reviews

#6127 Fix typos
  maths/integration_by_simpson_approx.py
Labels: enhancement

#6040 fixed mypy annotations for arithmetic_analysis
  arithmetic_analysis/gaussian_elimination.py
  arithmetic_analysis/in_static_equilibrium.py
  arithmetic_analysis/jacobi_iteration_method.py
  arithmetic_analysis/lu_decomposition.py
Labels: enhancement

#5803 Improve Project Euler problem 074 solution 2
  project_euler/problem_074/sol2.py
Labels: enhancement, stale

#6005 Update bucket_sort.py
  sorts/bucket_sort.py
Labels: enhancement

#5817 Add missing type annotations for `strings` directory
  strings/autocomplete_using_trie.py
  strings/detecting_english_programmatically.py
  strings/frequency_finder.py
  strings/word_occurrence.py
  strings/z_function.py
Labels: enhancement

#6126 Improve Code
  ciphers/enigma_machine2.py
  ciphers/hill_cipher.py
  data_structures/hashing/number_theory/prime_numbers.py
  divide_and_conquer/strassen_matrix_multiplication.py
  dynamic_programming/rod_cutting.py
  hashes/enigma_machine.py
  maths/integration_by_simpson_approx.py
  matrix/matrix_operation.py
  project_euler/problem_067/sol1.py
  sorts/external_sort.py
Labels: enhancement, awaiting reviews

#6154 Fix typo in word_occurrence.py
  strings/word_occurrence.py
Labels: enhancement, tests are failing

#6153 Fix `iter_merge_sort` bug
  conversions/octal_to_decimal.py
  sorts/iterative_merge_sort.py
Labels: enhancement

#6141 Improve Project Euler problem 145 solution 1
  DIRECTORY.md
  project_euler/problem_145/sol1.py
Labels: enhancement

#5882 Minmum path sum
  graphs/minimum_path_sum.py
Labels: awaiting reviews

#5552 Project Euler 68 Solution
  DIRECTORY.md
  project_euler/problem_068/__init__.py
  project_euler/problem_068/sol1.py
Labels: awaiting reviews
