Repository TheAlgorithms/Python, pull requests merged in 2022-07, with the labels that each got.

#6219 Tiny spelling error
  ciphers/enigma_machine2.py
Labels: enhancement

#6194 Add hamming distance
  strings/hamming_distance.py
Labels: awaiting reviews, tests are failing

#6236 Upgrade GitHub Actions
  .github/workflows/build.yml
  .github/workflows/directory_writer.yml
  .github/workflows/pre-commit.yml
  .github/workflows/project_euler.yml
  .pre-commit-config.yaml
  DIRECTORY.md
Labels: enhancement

#6230 MAINT: Updated f-string method
  ciphers/elgamal_key_generator.py
  ciphers/rsa_cipher.py
  ciphers/rsa_key_generator.py
  ciphers/transposition_cipher.py
  ciphers/transposition_cipher_encrypt_decrypt_file.py
  ciphers/vigenere_cipher.py
  data_structures/binary_tree/binary_search_tree.py
  hashes/chaos_machine.py
  machine_learning/gradient_boosting_regressor.py
  machine_learning/k_means_clust.py
  machine_learning/linear_regression.py
  matrix/sherman_morrison.py
  neural_network/convolution_neural_network.py
  other/lru_cache.py
  other/scoring_algorithm.py
  scheduling/shortest_job_first.py
  searches/binary_tree_traversal.py
  strings/min_cost_string_conversion.py
Labels: enhancement

#6245 pre-commit autoupdate: pyupgrade v2.34.0 -> v2.37.0
  .pre-commit-config.yaml
  arithmetic_analysis/bisection.py
  arithmetic_analysis/intersection.py
  arithmetic_analysis/newton_method.py
  boolean_algebra/quine_mc_cluskey.py
  ciphers/playfair_cipher.py
  computer_vision/horn_schunck.py
  data_structures/binary_tree/binary_search_tree_recursive.py
  data_structures/binary_tree/binary_tree_traversals.py
  data_structures/binary_tree/non_recursive_segment_tree.py
  data_structures/binary_tree/red_black_tree.py
  data_structures/heap/heap.py
  data_structures/heap/randomized_heap.py
  data_structures/heap/skew_heap.py
  data_structures/linked_list/circular_linked_list.py
  data_structures/queue/double_ended_queue.py
  data_structures/queue/linked_queue.py
  divide_and_conquer/convex_hull.py
  fractals/julia_sets.py
  graphs/prim.py
  linear_algebra/src/lib.py
  machine_learning/linear_discriminant_analysis.py
  maths/area_under_curve.py
  maths/euclidean_distance.py
  maths/euler_method.py
  maths/euler_modified.py
  maths/line_length.py
  maths/monte_carlo.py
  maths/numerical_integration.py
  maths/polynomial_evaluation.py
  maths/prime_numbers.py
  other/davisb_putnamb_logemannb_loveland.py
  other/lfu_cache.py
  other/lru_cache.py
  project_euler/problem_010/sol2.py
  project_euler/problem_025/sol2.py
  project_euler/problem_101/sol1.py
  project_euler/problem_107/sol1.py
  project_euler/problem_123/sol1.py
  scripts/build_directory_md.py
  web_programming/fetch_jobs.py
Labels: enhancement, awaiting reviews

#6240 Fixes: 6216 | Support vector machines
  machine_learning/support_vector_machines.py
Labels: awaiting reviews

#6246 Get rid of the Union
  .github/workflows/pre-commit.yml
  DIRECTORY.md
  project_euler/problem_101/sol1.py
Labels: enhancement, awaiting reviews

#6228 Unify primality checking
  DIRECTORY.md
  data_structures/hashing/double_hash.py
  data_structures/hashing/number_theory/prime_numbers.py
  maths/prime_check.py
  maths/primelib.py
Labels: enhancement

#6044 improved `prime_check` in math modules
  maths/prime_check.py
Labels: enhancement

#6250 fix: test failures
  maths/miller_rabin.py
  maths/prime_check.py
Labels: enhancement, bugfix

#5548 Added circle sort implementation
  sorts/circle_sort.py
Labels: awaiting merge

#6259 Improve Project Euler problem 145 solution 1
  DIRECTORY.md
  project_euler/problem_145/sol1.py
Labels: enhancement

#6263 Updated .gitignore for Visual Studio
  .gitignore
Labels: enhancement

#6265 renamed gcd() to greatest_comman_divisor()
  project_euler/problem_005/sol2.py
Labels: enhancement

#6267 Improve Project Euler problem 030 solution 1
  project_euler/problem_030/sol1.py
Labels: enhancement
