Repository TheAlgorithms/Python, pull requests merged in 2022-06, with the labels that each got.

#6165 Add Multi-Level-Feedback-Queue scheduling algorithm
  scheduling/multi_level_feedback_queue.py
Labels: tests are failing

#6169 Create non_preemptive_shortest_job_first.py
  scheduling/non_preemptive_shortest_job_first.py
Labels: awaiting reviews

#6190 make DIRECTORY.md paths relative
  DIRECTORY.md
  scripts/build_directory_md.py
Labels: enhancement, awaiting merge

#6017 Update basic_maths.py
  maths/basic_maths.py
Labels: enhancement

#6061 Wave
  strings/wave.py
Labels: awaiting reviews

#6201 Remove how-to example for support vector machine
  machine_learning/support_vector_machines.py
Labels: enhancement, help wanted, question
