Repository TheAlgorithms/Python, pull requests merged in 2022-10, with the labels that each got.

#6461 Fix docstring
  sorts/radix_sort.py
Labels: enhancement

#6529 Added fetch_quotes.py
  web_programming/fetch_quotes.py
Labels: awaiting reviews, require tests

#6542 fix: GitHub requires `.yml` extension
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: enhancement, awaiting reviews

#6559 Fix pre-commit.ci: additional_dependencies: [types-requests]
  .pre-commit-config.yaml
  DIRECTORY.md
Labels: enhancement

#6456 Update astar.py
  machine_learning/astar.py
Labels: enhancement

#6565 pre-commit.ci working so drop less powerful GHA
  .github/workflows/pre-commit.yml
Labels: enhancement

#6612 Add missing type hints in `matrix` directory
  matrix/count_islands_in_matrix.py
  matrix/matrix_class.py
  matrix/matrix_operation.py
  matrix/nth_fibonacci_using_matrix_exponentiation.py
  matrix/rotate_matrix.py
  matrix/searching_in_sorted_matrix.py
  matrix/sherman_morrison.py
  matrix/spiral_print.py
Labels: enhancement, awaiting reviews

#6845 Add Catalan number to maths
  DIRECTORY.md
  maths/catalan_number.py
Labels: awaiting reviews

#6864 Python program for Carmicheal Number
  maths/carmichael_number.py
Labels: hacktoberfest, require tests, hacktoberfest-accepted, require descriptive names

#7019 Add Equal Loudness Filter
  audio_filters/equal_loudness_filter.py
  audio_filters/loudness_curve.json
  requirements.txt
Labels: enhancement

#7044 Add typing to data_structures/heap/heap_generic.py
  data_structures/heap/heap_generic.py
Labels: enhancement

#7040 Add typing to data_structures/hashing/hash_table.py
  data_structures/hashing/hash_table.py
Labels: enhancement

#7037 Add typing to data_structures/queue/queue_on_pseudo_stack.py
  data_structures/queue/queue_on_pseudo_stack.py
Labels: enhancement

#7054 Add typing to maths/segmented_sieve.py
  maths/segmented_sieve.py
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#6441 Add volume of hollow circular cylinder, Exceptions
  maths/volume.py
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#7060 Add typing to maths/abs.py
  maths/abs.py
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#7057 Add typing to maths/ceil.py
  maths/ceil.py
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#7056 Add typing to maths/floor.py
  maths/floor.py
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#6442 Add surface area of cuboid, conical frustum
  maths/area.py
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#6877 added self organising maps algorithm in the machine learning section.
  machine_learning/self_organizing_map.py
Labels: hacktoberfest, require tests, hacktoberfest-accepted, require descriptive names

#7063 README.md: Lose LGTM badge because we don't use it
  DIRECTORY.md
  README.md
Labels: documentation

#6771 Added barcode_validator.py
  quantum/README.md
  strings/barcode_validator.py
Labels: documentation

#7064 Add typing to maths/add.py
  maths/add.py
Labels: enhancement

#7066 Add typing and snake casing to maths/decimal_isolate.py
  maths/decimal_isolate.py
Labels: enhancement

#7065 Add typing to maths/sum_of_arithmetic_series.py
  maths/sum_of_arithmetic_series.py
Labels: enhancement

#6840 Binary Search Tree Inorder Traversal Algorithm
  DIRECTORY.md
  data_structures/binary_tree/inorder_tree_traversal_2022.py
Labels: hacktoberfest, require tests, hacktoberfest-accepted

#7105 Add flake8-builtins to pre-commit and fix errors
  .flake8
  .pre-commit-config.yaml
  arithmetic_analysis/gaussian_elimination.py
  arithmetic_analysis/jacobi_iteration_method.py
  audio_filters/show_response.py
  backtracking/hamiltonian_cycle.py
  data_structures/binary_tree/avl_tree.py
  data_structures/linked_list/__init__.py
  data_structures/linked_list/singly_linked_list.py
  data_structures/queue/double_ended_queue.py
  data_structures/stacks/next_greater_element.py
  digital_image_processing/index_calculation.py
  dynamic_programming/optimal_binary_search_tree.py
  graphs/a_star.py
  graphs/dijkstra.py
  graphs/finding_bridges.py
  graphs/prim.py
  hashes/djb2.py
  hashes/sdbm.py
  maths/armstrong_numbers.py
  maths/bailey_borwein_plouffe.py
  maths/kadanes.py
  maths/prime_numbers.py
  maths/sum_of_arithmetic_series.py
  neural_network/2_hidden_layers_neural_network.py
  neural_network/convolution_neural_network.py
  neural_network/perceptron.py
  project_euler/problem_065/sol1.py
  project_euler/problem_070/sol1.py
  sorts/odd_even_sort.py
  strings/snake_case_to_camel_pascal_case.py
Labels: enhancement

#7081 refined readme.md
  README.md
Labels: hacktoberfest, hacktoberfest-accepted, documentation

#6995 Create binary_search_matrix.py
  matrix/binary_search_matrix.py
Labels: awaiting reviews, hacktoberfest, hacktoberfest-accepted

#7152 Remove extra Semicolon
  data_structures/queue/linked_queue.py
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#7167 refactor: move flake8 config
  .flake8
  .pre-commit-config.yaml
Labels: enhancement, awaiting reviews

#7116 Doctest output simpler version
  conversions/volume_conversions.py
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#7196 refactor: Make code more understandable
  data_structures/binary_tree/binary_tree_traversals.py
Labels: enhancement

#7189 remove useless bool() call
  boolean_algebra/norgate.py
Labels: enhancement

#7183 Added astronomical_length_scale_conversion.py
  conversions/astronomical_length_scale_conversion.py
Labels: hacktoberfest, hacktoberfest-accepted

#7198 refactor: Replace `list()` and `dict()` calls with literals
  data_structures/binary_tree/binary_search_tree.py
  data_structures/heap/heap_generic.py
  data_structures/trie/trie.py
  graphs/frequent_pattern_graph_miner.py
  maths/greedy_coin_change.py
  other/davisb_putnamb_logemannb_loveland.py
  project_euler/problem_107/sol1.py
  searches/tabu_search.py
  sorts/msd_radix_sort.py
  strings/aho_corasick.py
Labels: enhancement

#7205 chore: remove inactive user from CODEOWNERS
  .github/CODEOWNERS
  DIRECTORY.md
Labels: enhancement

#7162 feat: Binary tree node sum (#7020)
  DIRECTORY.md
  data_structures/binary_tree/binary_tree_node_sum.py
Labels: awaiting reviews

#7235 Add Flake8 comprehensions to pre-commit
  .pre-commit-config.yaml
  ciphers/onepad_cipher.py
  ciphers/rail_fence_cipher.py
  data_structures/hashing/hash_table.py
  data_structures/linked_list/merge_two_lists.py
  dynamic_programming/fractional_knapsack.py
  graphs/bellman_ford.py
  graphs/frequent_pattern_graph_miner.py
  hashes/enigma_machine.py
  maths/primelib.py
  matrix/spiral_print.py
  other/davisb_putnamb_logemannb_loveland.py
  project_euler/problem_042/solution42.py
  project_euler/problem_052/sol1.py
  project_euler/problem_062/sol1.py
  project_euler/problem_067/sol1.py
  project_euler/problem_109/sol1.py
  project_euler/problem_551/sol1.py
  sorts/radix_sort.py
  strings/aho_corasick.py
Labels: enhancement, awaiting reviews

#7141 Add algorithm for Casimir Effect
  physics/casimir_effect.py
Labels: awaiting reviews, hacktoberfest, hacktoberfest-accepted

#7197 types: Update binary search tree typehints
  data_structures/binary_tree/binary_search_tree.py
Labels: enhancement, awaiting reviews

#6912 Misc fixes across multiple algorithms
  compression/huffman.py
  data_structures/linked_list/is_palindrome.py
  digital_image_processing/filters/local_binary_pattern.py
  fuzzy_logic/fuzzy_operations.py
  graphs/dijkstra_algorithm.py
  graphs/directed_and_undirected_(weighted)_graph.py
  hashes/hamming_code.py
  linear_algebra/src/test_linear_algebra.py
  maths/extended_euclidean_algorithm.py
  maths/jaccard_similarity.py
  matrix/matrix_class.py
  project_euler/problem_001/sol7.py
  project_euler/problem_042/solution42.py
  project_euler/problem_067/sol1.py
  project_euler/problem_089/sol1.py
  requirements.txt
  scheduling/first_come_first_served.py
  scheduling/multi_level_feedback_queue.py
  web_programming/emails_from_url.py
Labels: enhancement

#7277 Change to https.
  fractals/julia_sets.py
  fractals/sierpinski_triangle.py
  machine_learning/lstm/lstm_prediction.py
  machine_learning/sequential_minimum_optimization.py
  maths/matrix_exponentiation.py
  maths/test_prime_check.py
  physics/n_body_simulation.py
  strings/frequency_finder.py
  web_programming/crawl_google_results.py
  web_programming/crawl_google_scholar_citation.py
  web_programming/current_weather.py
  web_programming/giphy.py
Labels: enhancement, awaiting reviews

#7262 refactor: Move constants outside of variable scope
  ciphers/bifid.py
  ciphers/brute_force_caesar_cipher.py
  ciphers/polybius.py
  compression/peak_signal_to_noise_ratio.py
  conversions/binary_to_hexadecimal.py
  conversions/decimal_to_any.py
  conversions/roman_numerals.py
  geodesy/haversine_distance.py
  geodesy/lamberts_ellipsoidal_distance.py
  hashes/adler32.py
  physics/n_body_simulation.py
  project_euler/problem_054/test_poker_hand.py
  project_euler/problem_064/sol1.py
  project_euler/problem_097/sol1.py
  project_euler/problem_125/sol1.py
  sorts/radix_sort.py
  web_programming/fetch_quotes.py
Labels: enhancement

#7080 Added some more comments to volume.py in maths folder
  maths/volume.py
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#7319 Fix broken links by PR #7277
  bit_manipulation/count_1s_brian_kernighan_method.py
  machine_learning/sequential_minimum_optimization.py
  physics/n_body_simulation.py
Labels: enhancement

#7338 Add `flake8-broken-line` to `pre-commit`
  .pre-commit-config.yaml
  project_euler/problem_008/sol1.py
  project_euler/problem_008/sol3.py
Labels: enhancement

#7339 Follow Flake8 pep3101 and remove modulo formatting
  ciphers/elgamal_key_generator.py
  ciphers/rsa_key_generator.py
  dynamic_programming/edit_distance.py
  genetic_algorithm/basic_string.py
  graphs/minimum_spanning_tree_boruvka.py
  machine_learning/linear_regression.py
  matrix/sherman_morrison.py
  neural_network/back_propagation_neural_network.py
  neural_network/convolution_neural_network.py
Labels: enhancement

#7340 ci: Add ``yesqa`` (flake8-plugin) to ``pre-commit``
  .pre-commit-config.yaml
Labels: enhancement

#6918 [Matrix] Max area of island problem solved DFS algorithm
  matrix/max_area_of_island.py
Labels: awaiting reviews

#7409 Create minmax.py
  backtracking/minmax.py
Labels: hacktoberfest, hacktoberfest-accepted

#7403 Create combination_sum.py
  DIRECTORY.md
  backtracking/combination_sum.py
Labels: hacktoberfest, hacktoberfest-accepted

#7368 Implemented Gelu Function
  maths/gaussian_error_linear_unit.py
Labels: hacktoberfest, hacktoberfest-accepted

#7417 Remove references to depreciated QasmSimulator
  DIRECTORY.md
  quantum/deutsch_jozsa.py
  quantum/half_adder.py
  quantum/not_gate.py
  quantum/q_full_adder.py
  quantum/quantum_entanglement.py
  quantum/ripple_adder_classic.py
  quantum/single_qubit_measure.py
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#7405 Create graphs/dijkstra_alternate.py
  graphs/dijkstra_alternate.py
Labels: awaiting reviews

#7106 XGBoost Classifier
  machine_learning/xgboostclassifier.py
Labels: awaiting reviews

#7451 Maclaurin series approximation of sin
  maths/maclaurin_sin.py
Labels: awaiting reviews, hacktoberfest, hacktoberfest-accepted

#7499 Remove some print statements within algorithmic functions
  DIRECTORY.md
  cellular_automata/game_of_life.py
  digital_image_processing/index_calculation.py
  divide_and_conquer/max_subarray_sum.py
  divide_and_conquer/strassen_matrix_multiplication.py
  dynamic_programming/longest_sub_array.py
  dynamic_programming/max_non_adjacent_sum.py
  dynamic_programming/subset_generation.py
  dynamic_programming/sum_of_subset.py
  machine_learning/forecasting/run.py
Labels: enhancement, awaiting reviews

#7504 Created sum_of_harmonic_series.py
  maths/sum_of_harmonic_series.py
Labels: hacktoberfest, hacktoberfest-accepted

#7534 Basic string grammar fix
  genetic_algorithm/basic_string.py
Labels: enhancement, awaiting reviews

#7522 Simplify the code in maclaurin_series
  maths/maclaurin_series.py
Labels: enhancement

#7429 Reduced Time Complexity to O(sqrt(n))
  maths/factors.py
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#7349 Create superdense_coding.py
  quantum/superdense_coding.py
Labels: hacktoberfest, hacktoberfest-accepted

#7556 Replace deprecated `qasm_simulator` with `aer_simulator` (#7308)
  quantum/superdense_coding.py
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#7550 Rename xgboostclassifier.py to xgboost_classifier.py
  DIRECTORY.md
  machine_learning/xgboost_classifier.py
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#7538 Add web program to fetch top 10 real time billionaires using the forbes API.
  requirements.txt
  web_programming/get_top_billioners.py
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#7558 Fix doctest tracebacks
  conversions/pressure_conversions.py
  electronics/carrier_concentration.py
  electronics/electric_power.py
  maths/nevilles_method.py
Labels: enhancement

#7566 fix: Fix line too long in doctest
  web_programming/get_top_billioners.py
Labels: enhancement

#7564 Update comments in check_pangram.py script
  strings/check_pangram.py
  strings/is_pangram.py
Labels: enhancement, require tests

#7271 Update knapsack.py
  dynamic_programming/knapsack.py
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#7589 Update count_number_of_one_bits.py
  bit_manipulation/count_number_of_one_bits.py
Labels: enhancement, awaiting reviews

#7575 Add Spain National ID validator (#7574)
  strings/is_spain_national_id.py
Labels: awaiting reviews

#7604 Fix run error in Project Euler problem 104 solution 1
  DIRECTORY.md
  project_euler/problem_104/sol1.py
Labels: enhancement

#7620 Create kinetic_energy.py
  physics/kinetic_energy.py
Labels: hacktoberfest, hacktoberfest-accepted

#6255 corrected the shape of trajectory
  physics/horizontal_projectile_motion.py
Labels: enhancement

#7486 Updated documentation of cnn_classification.py
  computer_vision/cnn_classification.py
Labels: enhancement

#7547 Add Cramer's rule for solving system of linear equations in two variables
  matrix/cramers_rule_2x2.py
Labels: hacktoberfest, hacktoberfest-accepted

#7438 Included area of n sided regular polygon
  maths/area.py
Labels: enhancement

#7608 Added function that checks if a string is an isogram
  strings/is_isogram.py
Labels: awaiting reviews, tests are failing

#6909 Write a proper implementation for base16
  ciphers/base16.py
Labels: enhancement, awaiting reviews, hacktoberfest, hacktoberfest-accepted

#7355 added support for inverse of 3x3 matrix
  matrix/inverse_of_matrix.py
Labels: enhancement

#7673 Create largest_square_area_in_matrix.py
  matrix/largest_square_area_in_matrix.py
Labels: require tests

#7674 Update spiral_print.py
  matrix/spiral_print.py
Labels: enhancement

#7683 Rename quantum_random.py to quantum_random.py.DISABLED.txt
  DIRECTORY.md
  quantum/quantum_random.py.DISABLED.txt
Labels: enhancement, awaiting reviews

#7696 Updated a typo in print statement
  strings/barcode_validator.py
Labels: enhancement

#7694 Calculate GST Amount
  financial/price_plus_tax.py
Labels: hacktoberfest, hacktoberfest-accepted

#7729 refactor: Fix matrix display deprecation
  machine_learning/xgboost_classifier.py
Labels: enhancement

#7744 Indent `...` for visual purposes
  arithmetic_analysis/bisection.py
  arithmetic_analysis/intersection.py
  arithmetic_analysis/jacobi_iteration_method.py
  arithmetic_analysis/lu_decomposition.py
  arithmetic_analysis/newton_method.py
  arithmetic_analysis/newton_raphson_new.py
  backtracking/knight_tour.py
  conversions/binary_to_decimal.py
  conversions/binary_to_hexadecimal.py
  conversions/binary_to_octal.py
  conversions/decimal_to_any.py
  conversions/decimal_to_binary.py
  conversions/decimal_to_binary_recursion.py
  conversions/decimal_to_hexadecimal.py
  conversions/hex_to_bin.py
  conversions/hexadecimal_to_decimal.py
  conversions/octal_to_decimal.py
  conversions/temperature_conversions.py
  data_structures/binary_tree/binary_search_tree.py
  data_structures/binary_tree/binary_tree_mirror.py
  data_structures/binary_tree/number_of_possible_binary_trees.py
  data_structures/linked_list/doubly_linked_list.py
  data_structures/linked_list/singly_linked_list.py
  data_structures/queue/linked_queue.py
  data_structures/queue/priority_queue_using_list.py
  data_structures/stacks/infix_to_postfix_conversion.py
  data_structures/stacks/stack_with_singly_linked_list.py
  dynamic_programming/longest_common_substring.py
  genetic_algorithm/basic_string.py
  linear_algebra/src/lib.py
  machine_learning/similarity_search.py
  maths/bisection.py
  maths/catalan_number.py
  maths/fibonacci.py
  maths/maclaurin_series.py
  maths/proth_number.py
  maths/sylvester_sequence.py
  maths/zellers_congruence.py
  neural_network/perceptron.py
  project_euler/problem_004/sol1.py
  project_euler/problem_010/sol3.py
  searches/interpolation_search.py
  sorts/bead_sort.py
  sorts/msd_radix_sort.py
  strings/barcode_validator.py
  strings/join.py
Labels: enhancement, awaiting reviews

#6879 Added spheres union
  maths/volume.py
Labels: enhancement

#7759 Remove unnecessary else statement
  maths/karatsuba.py
Labels: enhancement

#7733 Remove useless code in doctests
  backtracking/hamiltonian_cycle.py
  computer_vision/flip_augmentation.py
  computer_vision/mosaic_augmentation.py
  data_structures/heap/binomial_heap.py
  data_structures/heap/heap.py
  data_structures/heap/min_heap.py
  data_structures/linked_list/skip_list.py
  graphs/gale_shapley_bigraph.py
  graphs/graph_list.py
  graphs/minimum_spanning_tree_prims2.py
  graphs/random_graph_generator.py
  machine_learning/local_weighted_learning/local_weighted_learning.py
  maths/polynomial_evaluation.py
  maths/radix2_fft.py
  matrix/matrix_class.py
  searches/simple_binary_search.py
  sorts/bitonic_sort.py
  sorts/normal_distribution_quick_sort.md
  sorts/recursive_insertion_sort.py
  web_programming/reddit.py
  web_programming/search_books_by_isbn.py
Labels: documentation

#7749 Refactoring the syntax using list comprehension
  strings/detecting_english_programmatically.py
Labels: enhancement

#7761 fix typo in caesar_cipher.py
  ciphers/caesar_cipher.py
Labels: enhancement

#7737 Adopt Python >= 3.8 assignment expressions using auto-walrus
  .pre-commit-config.yaml
  DIRECTORY.md
  ciphers/enigma_machine2.py
  data_structures/linked_list/doubly_linked_list_two.py
  dynamic_programming/fibonacci.py
  machine_learning/sequential_minimum_optimization.py
  strings/indian_phone_validator.py
Labels: enhancement

#7794 Update PR template
  .github/pull_request_template.md
Labels: documentation

#7757 Update maximum_subarray.py
  other/maximum_subarray.py
Labels: enhancement

#7672 Create combination_sum_iv.py
  dynamic_programming/combination_sum_iv.py
Labels: require tests, require descriptive names

#7765 Update breadth_first_search_2.py
  graphs/breadth_first_search_2.py
Labels: enhancement

#7821 Format docs
  machine_learning/data_transformations.py
  physics/kinetic_energy.py
  sorts/merge_sort.py
  sorts/odd_even_sort.py
Labels: enhancement

#7666 Create potential_energy.py
  physics/potential_energy.py
Labels: awaiting reviews

#7840 Add running doctest to pytest default
  .coveragerc
  .github/workflows/build.yml
  DIRECTORY.md
  pyproject.toml
  pytest.ini
Labels: enhancement

#7819 Rename files to have matching prefixes
  graphs/breadth_first_search_shortest_path_2.py
  graphs/breadth_first_search_zero_one_shortest_path.py
Labels: enhancement

#7745 Update password_generator.py
  other/password_generator.py
Labels: enhancement

#7843 Fix yesqa hook
  .pre-commit-config.yaml
  DIRECTORY.md
  data_structures/binary_tree/non_recursive_segment_tree.py
  digital_image_processing/index_calculation.py
  genetic_algorithm/basic_string.py
  maths/prime_sieve_eratosthenes.py
Labels: enhancement

#7614 added algo for finding permutations of an array
  data_structures/arrays/permutations.py
Labels: awaiting reviews

#7354 Added algorithm for Text Justification in Strings
  strings/text_justification.py
Labels: require tests

#7845 Correcting typos in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#6983 Resonant Frequency & Electrical Impedance
  electronics/electrical_impedance.py
  electronics/resonant_frequency.py
Labels: awaiting reviews

#7001 Added cosine similarity
  machine_learning/similarity_search.py
Labels: enhancement

#7844 Remove file-level flake8 suppression
  DIRECTORY.md
  data_structures/heap/binomial_heap.py
  other/activity_selection.py
  searches/binary_tree_traversal.py
Labels: enhancement

#7848 Update kinetic_energy.py
  physics/kinetic_energy.py
Labels: enhancement

#7533 matrix/count_paths.py
  matrix/count_paths.py
Labels: awaiting reviews

#7790 Added Manhattan distance algorithm
  maths/manhattan_distance.py
Labels: awaiting reviews

#7867 Update docs
  .pre-commit-config.yaml
  CONTRIBUTING.md
  DIRECTORY.md
Labels: documentation, ON HOLD: Final hours of Hacktoberfest 2022

#7866 Updated info
  sorts/README.md
Labels: awaiting reviews, documentation, ON HOLD: Final hours of Hacktoberfest 2022

#7869 fix(quantum): Correct simulator deprecation
  quantum/quantum_teleportation.py
Labels: enhancement

#6467 Description of Double hasing
  data_structures/hashing/double_hash.py
Labels: enhancement, awaiting reviews

#6583 For the better understanding of time taken.
  sorts/bubble_sort.py
Labels: enhancement

#6742 added sumset.py Fixes: #{6563}
  DIRECTORY.md
  maths/sumset.py
Labels: awaiting reviews

#6743 Added Readme file to document the hashing algorithm.
  hashes/README.md
Labels: documentation

#7191 refactor: use abs() and inplace operation
  maths/sum_of_digits.py
Labels: enhancement

#7850 Added Builtin Voltage
  electronics/builtin_voltage.py
  hashes/elf.py
Labels: ON HOLD: Final hours of Hacktoberfest 2022

#7003 Added mean absolute error in linear regression
  machine_learning/linear_regression.py
Labels: enhancement, awaiting reviews

#7171 add Levinstein distance with Dynamic Programming: up -> down approach
  dynamic_programming/min_distance_up_bottom.py
Labels: require tests

#7222 Added code for palindrome partitioning problem under dynamic programming
  dynamic_programming/palindrome_partitioning.py
Labels: awaiting reviews

#7234 Added algorithm for finding index of rightmost set bit
  bit_manipulation/index_of_rightmost_set_bit.py
Labels: tests are failing

#7896 Shear stress: typo + Wikipedia URL
  physics/shear_stress.py
Labels: enhancement

#6782 Created equivalent_resistance under Electronics
  electronics/resistor_equivalence.py
Labels: awaiting reviews

#7347 Refactor bottom-up edit distance function to be class method
  DIRECTORY.md
  dynamic_programming/edit_distance.py
Labels: enhancement, awaiting reviews

#6591 Test on Python 3.11
  .github/workflows/build.yml
  CONTRIBUTING.md
  DIRECTORY.md
  requirements.txt
Labels: enhancement

#7901 Modified 'pascal_triangle.py' program
  other/pascal_triangle.py
Labels: enhancement

#6606 Dodecahedron surface area and volume
  maths/dodecahedron.py
Labels: awaiting reviews

#6682 create quantum_fourier_transform
  quantum/q_fourier_transform.py
Labels: awaiting reviews, hacktoberfest, tests are failing, hacktoberfest-accepted

#7906 Added Torus surface area
  maths/area.py
Labels: enhancement, awaiting reviews, ON HOLD: Final hours of Hacktoberfest 2022

#7905 Torus volume
  maths/volume.py
Labels: enhancement, awaiting reviews, ON HOLD: Final hours of Hacktoberfest 2022

#7921 Added a Hubble Parameter calculator file
  physics/hubble_parameter.py
Labels: tests are failing
