Repository TheAlgorithms/Python, pull requests merged in 2022-09, with the labels that each got.

#6348 Update README.md
  README.md
Labels: documentation

#6328 Fix Max Fenwick Tree
  data_structures/binary_tree/maximum_fenwick_tree.py
Labels: enhancement, awaiting reviews

#6258 Unify `O(sqrt(N))` `is_prime` functions under `project_euler`
  project_euler/problem_003/sol1.py
  project_euler/problem_007/sol1.py
  project_euler/problem_007/sol2.py
  project_euler/problem_007/sol3.py
  project_euler/problem_010/sol1.py
  project_euler/problem_010/sol2.py
  project_euler/problem_027/sol1.py
  project_euler/problem_037/sol1.py
  project_euler/problem_041/sol1.py
  project_euler/problem_046/sol1.py
  project_euler/problem_049/sol1.py
  project_euler/problem_058/sol1.py
Labels: enhancement, awaiting merge

#6225 Add Optimized Shell Sort
  DIRECTORY.md
  sorts/shrink_shell_sort.py
Labels: awaiting reviews

#6367 Fix minor typo and add matrix dimension check
  matrix/inverse_of_matrix.py
Labels: enhancement, awaiting reviews

#6305 Add Project Euler problem 116 solution 1
  DIRECTORY.md
  matrix/inverse_of_matrix.py
  project_euler/problem_116/__init__.py
  project_euler/problem_116/sol1.py
Labels: stale
