Repository TheAlgorithms/Python, pull requests merged in 2023-03, with the labels that each got.

#8045 Reduce the complexity of other/scoring_algorithm.py
  other/scoring_algorithm.py
Labels: enhancement

#6872 Add Project Euler problem 117 solution 1
  DIRECTORY.md
  project_euler/problem_117/__init__.py
  project_euler/problem_117/sol1.py
Labels: awaiting reviews

#8158 Add circular convolution
  electronics/circular_convolution.py
Labels: awaiting reviews

#8166 Reduce the complexity of backtracking/word_search.py
  backtracking/word_search.py
Labels: enhancement, awaiting reviews

#8163 docs: add the other/miscellaneous form
  .github/ISSUE_TEMPLATE/other.yml
Labels: awaiting reviews, documentation

#8179 Add Project Euler problem 131 solution 1
  DIRECTORY.md
  project_euler/problem_131/__init__.py
  project_euler/problem_131/sol1.py
Labels: awaiting reviews

#8184 Replace flake8 with ruff
  CONTRIBUTING.md
  audio_filters/equal_loudness_filter.py.broken.txt
  data_structures/binary_tree/red_black_tree.py
  digital_image_processing/change_contrast.py
  maths/is_square_free.py
  maths/mobius_function.py
  other/linear_congruential_generator.py
  pyproject.toml
  quantum/ripple_adder_classic.py
Labels: awaiting reviews, documentation

#8551 New gitter link added or replaced
  .github/stale.yml
  .pre-commit-config.yaml
  CONTRIBUTING.md
  README.md
  hashes/sha1.py
  machine_learning/sequential_minimum_optimization.py
  neural_network/convolution_neural_network.py
  project_euler/README.md
  pyproject.toml
  web_programming/download_images_from_google_query.py
Labels: invalid, documentation

#8546 Fix broken links to Gitter community
  .github/stale.yml
  CONTRIBUTING.md
  README.md
  project_euler/README.md
Labels: documentation

#8165 Reduce the complexity of graphs/bi_directional_dijkstra.py
  graphs/bi_directional_dijkstra.py
  pyproject.toml
Labels: enhancement

#8570 Update cnn_classification.py
  computer_vision/cnn_classification.py
Labels: enhancement

#8541 Update receive_file.py
  file_transfer/receive_file.py
Labels: enhancement, awaiting reviews
