Repository TheAlgorithms/Python, pull requests merged in 2023-05, with the labels that each got.

#8702 Fix docstring in present_value.py
  DIRECTORY.md
  financial/present_value.py
Labels: enhancement, awaiting reviews

#8690 Update and_gate.py
  boolean_algebra/and_gate.py
Labels: enhancement, awaiting reviews

#7995 Switch case
  strings/string_switch_case.py
Labels: awaiting reviews

#6708 adding the remove digit algorithm
  maths/remove_digit.py
Labels: awaiting reviews

#7811 Create maximum_subsequence.py
  DIRECTORY.md
  other/maximum_subsequence.py
Labels: awaiting reviews

#8732 Correct ruff failures
  DIRECTORY.md
  conversions/prefix_conversions_string.py
  conversions/rgb_hsv_conversion.py
  digital_image_processing/test_digital_image_processing.py
  divide_and_conquer/strassen_matrix_multiplication.py.BROKEN
  dynamic_programming/fibonacci.py
  maths/euclidean_distance.py
  physics/horizontal_projectile_motion.py
  searches/binary_tree_traversal.py
Labels: awaiting reviews

#8740 Added odd_sieve.py
  maths/odd_sieve.py
Labels: awaiting reviews

#8036 Add h index
  DIRECTORY.md
  other/h_index.py
Labels: awaiting reviews

#7937 Create guess_the_number_search.py
  other/guess_the_number_search.py
Labels: awaiting reviews

#8746 Fixes broken "Create guess_the_number_search.py"
  DIRECTORY.md
  other/guess_the_number_search.py
Labels: enhancement, awaiting reviews

#8763 Mark fetch anime and play as broken
  DIRECTORY.md
  web_programming/fetch_anime_and_play.py.BROKEN
Labels: awaiting reviews

#8760 Dual Number Automatic Differentiation
  DIRECTORY.md
  maths/dual_number_automatic_differentiation.py
Labels: tests are failing

#8766 fix typo graphs/greedy_best_first.py
  graphs/greedy_best_first.py
Labels: enhancement

#8768 Rename is_palindrome.py to is_int_palindrome.py
  DIRECTORY.md
  maths/is_int_palindrome.py
Labels: enhancement, awaiting reviews

#8102 Update permutations.py
  data_structures/arrays/permutations.py
Labels: enhancement, awaiting reviews

#8687 Added rank of matrix in linear algebra
  linear_algebra/src/rank_of_matrix.py
Labels: awaiting reviews
