Repository TheAlgorithms/Python, pull requests merged in 2023-07, with the labels that each got.

#8879 [Upgrade Ruff] Fix all errors raised from ruff
  .pre-commit-config.yaml
  cellular_automata/game_of_life.py
  data_structures/binary_tree/red_black_tree.py
  data_structures/trie/radix_tree.py
  divide_and_conquer/convex_hull.py
  graphs/directed_and_undirected_(weighted)_graph.py
  graphs/edmonds_karp_multiple_source_and_sink.py
  maths/factorial.py
  maths/primelib.py
  other/davisb_putnamb_logemannb_loveland.py
  project_euler/problem_009/sol3.py
  quantum/ripple_adder_classic.py
  strings/min_cost_string_conversion.py
  web_programming/convert_number_to_words.py
Labels: awaiting reviews

#8875 Small docstring time complexity fix in number_container _system
  other/number_container_system.py
Labels: tests are failing

#8887 Add Docker devcontainer configuration files
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
Labels: awaiting reviews

#8892 Fix ruff rules ISC flake8-implicit-str-concat
  ciphers/diffie_hellman.py
  compression/burrows_wheeler.py
  neural_network/input_data.py
  pyproject.toml
  strings/is_srilankan_phone_number.py
  web_programming/world_covid19_stats.py
Labels: enhancement

#8900 Fix failing build due to missing requirement
  requirements.txt
Labels: enhancement

#8889 Reimplement polynomial_regression.py
  DIRECTORY.md
  machine_learning/polymonial_regression.py
  machine_learning/polynomial_regression.py
Labels: enhancement

#8902 Disable quantum/quantum_random.py (attempt 2)
  DIRECTORY.md
  quantum/quantum_random.py.DISABLED.txt
Labels: enhancement

#8905 Fix greyscale computation and inverted coords
  digital_image_processing/dithering/burkes.py
Labels: awaiting reviews

#4630 Pythonic implementation of LRU Cache
  other/lru_cache_pythonic.py
Labels: No Response, awaiting reviews

#8726 add reverse_inorder traversal to binary_tree_traversals.py
  data_structures/binary_tree/binary_tree_traversals.py
Labels: stale, awaiting reviews

#8644 Fix linear_search docstring return value
  searches/linear_search.py
Labels: enhancement, awaiting reviews

#8608 Enhance the implementation of Queue using list
  data_structures/queue/queue_by_list.py
  data_structures/queue/queue_on_list.py
Labels: enhancement, awaiting reviews

#8718 Handle empty input case in Segment Tree build process
  data_structures/binary_tree/segment_tree.py
Labels: awaiting reviews

#5802 Update `sorts/bubble_sort.py`
  sorts/bubble_sort.py
Labels: enhancement, awaiting reviews

#4921 Update game_of_life.py
  cellular_automata/game_of_life.py
Labels: enhancement, awaiting reviews
