Repository TheAlgorithms/Python, pull requests merged in 2023-11, with the labels that each got.

#11105 Added doctest to hash_map.py
  data_structures/hashing/hash_map.py
Labels: awaiting reviews

#11143 Added doctest to decision_tree.py
  machine_learning/decision_tree.py
Labels: awaiting reviews

#11141 Added doctest to binary_search_tree.py
  data_structures/binary_tree/binary_search_tree.py
Labels: awaiting reviews

#10902 Create get_ip_geolocation.py
  web_programming/get_ip_geolocation.py
Labels: awaiting reviews

#11134 Data structures/arrays/triplet sum
  data_structures/arrays/find_triplets_with_0_sum.py
Labels: awaiting reviews

#11135 Added doctest to detecting_english_programmatically.py
  strings/detecting_english_programmatically.py
Labels: enhancement

#11136 Added doctest to string_switch_case.py
  strings/string_switch_case.py
Labels: awaiting reviews

#11149 Added doctest to stack.py
  data_structures/stacks/stack.py
Labels: awaiting reviews

#11129 Added doctest to heap.py
  data_structures/heap/heap.py
Labels: enhancement, awaiting changes, awaiting reviews

#11156 Fix ignore venv in build_directory_md.py
  scripts/build_directory_md.py
  web_programming/get_imdbtop.py.DISABLED
Labels: awaiting reviews, tests are failing

#11163 add graphs/ant_colony_optimization_algorithms.py
  graphs/ant_colony_optimization_algorithms.py
Labels: awaiting reviews, require descriptive names

#11158 Bug fix combinations
  backtracking/all_combinations.py
Labels: enhancement, awaiting reviews

#11155 Create Spearman's rank correlation coefficient
  maths/spearman_rank_correlation_coefficient.py
Labels: awaiting reviews

#11145 Added doctest to binary_search_tree.py
  data_structures/binary_tree/binary_search_tree.py
Labels: awaiting reviews
