Repository TheAlgorithms/Python, pull requests merged in 2023-08, with the labels that each got.

#8625 Window closing fix
  fractals/sierpinski_triangle.py
Labels: enhancement, awaiting reviews

#8932 improvements to jump_search.py
  searches/jump_search.py
Labels: awaiting reviews

#8936 Fix ruff errors
  DIRECTORY.md
  conversions/length_conversion.py
  conversions/pressure_conversions.py
  conversions/volume_conversions.py
  data_structures/binary_tree/distribute_coins.py
  electronics/electric_power.py
  graphs/bi_directional_dijkstra.py
  maths/area_under_curve.py
  maths/decimal_to_fraction.py
  maths/line_length.py
  maths/numerical_integration.py
  maths/polynomials/single_indeterminate_operations.py
  maths/series/geometric_series.py
  maths/series/p_series.py
  maths/volume.py
  matrix/matrix_class.py
  matrix/matrix_operation.py
  matrix/searching_in_sorted_matrix.py
  matrix/sherman_morrison.py
  neural_network/input_data.py.DEPRECATED.txt
  web_programming/covid_stats_via_xpath.py
Labels: enhancement, invalid, awaiting reviews

#8942 updated the URL and HTML tags for scrapping yahoo finance
  web_programming/current_stock_price.py
Labels: awaiting reviews

#8899 Create wa-tor algorithm
  DIRECTORY.md
  cellular_automata/wa_tor.py
Labels: awaiting reviews

#6321 Add: Two Regex match algorithm (Recursive & DP)
  dynamic_programming/regex_match.py
Labels: awaiting reviews

#6356 Added implementation for Tribonacci sequence using dp
  dynamic_programming/tribonacci.py
Labels: awaiting reviews

#8957 Update run.py in machine_learning/forecasting
  DIRECTORY.md
  machine_learning/forecasting/ex_data.csv
  machine_learning/forecasting/run.py
Labels: awaiting reviews

#8919 Added functions to calculate temperature of an ideal gas and number o…
  physics/ideal_gas_law.py
Labels: awaiting reviews

#8053 Remove a slash in path to save the file correctly on Linux
  computer_vision/flip_augmentation.py
Labels: enhancement, awaiting reviews

#8959 Fix minor typing errors in maths/
  digital_image_processing/morphological_operations/erosion_operation.py
  digital_image_processing/rotation/rotation.py
  maths/average_median.py
  maths/euler_modified.py
  maths/gaussian_error_linear_unit.py
  maths/jaccard_similarity.py
  maths/newton_raphson.py
  maths/qr_decomposition.py
  maths/sigmoid.py
  maths/tanh.py
Labels: awaiting reviews

#8775 Fix greedy_best_first
  graphs/greedy_best_first.py
Labels: enhancement, awaiting reviews

#8693 BST and RSA doctest
  ciphers/rsa_key_generator.py
  data_structures/binary_tree/binary_search_tree.py
Labels: awaiting reviews

#6846 Added Continued fractions
  DIRECTORY.md
  maths/continued_fraction.py
Labels: awaiting reviews

#8610 Fix `mypy` errors in `maths/gaussian_error_linear_unit.py`
  maths/gaussian_error_linear_unit.py
Labels: enhancement, awaiting reviews

#8843 Fix simplex.py
  linear_programming/simplex.py
Labels: awaiting reviews

#5786 Fix `sorts/bucket_sort.py` implementation
  DIRECTORY.md
  sorts/bucket_sort.py
Labels: enhancement, awaiting reviews

#8970 Fix get top billionaires BROKEN file
  DIRECTORY.md
  web_programming/get_top_billionaires.py
Labels: awaiting reviews

#8988 Unmark fetch anime and play as BROKEN and fix type errors
  DIRECTORY.md
  web_programming/fetch_anime_and_play.py
Labels: enhancement, awaiting reviews

#8949 Octal to Binary Convert
  conversions/octal_to_binary.py
Labels: awaiting reviews

#8964 Update arc_length.py
  maths/arc_length.py
Labels: awaiting reviews

#8967 Create langtons ant algorithm
  DIRECTORY.md
  cellular_automata/langtons_ant.py
Labels: awaiting reviews

#9007 Fix type errors in permutations
  data_structures/arrays/permutations.py
Labels: awaiting reviews

#8787 Updated postfix_evaluation.py to support Unary operators
  data_structures/stacks/evaluate_postfix_notations.py
  data_structures/stacks/postfix_evaluation.py
Labels: awaiting reviews
