Repository TheAlgorithms/Python, pull requests merged in 2023-09, with the labels that each got.

#6677 Style sigmoid function in harmony with pep guideness
  neural_network/back_propagation_neural_network.py
Labels: awaiting reviews

#8004 Texture analysis using Haralick Descriptors for Computer Vision tasks
  computer_vision/haralick_descriptors.py
  requirements.txt
Labels: awaiting reviews

#9009 Fix get amazon product data erroring due to whitespace in headers
  web_programming/get_amazon_product_data.py
Labels: enhancement, awaiting reviews

#9023 Created harshad_numbers.py
  maths/harshad_numbers.py
Labels: awaiting reviews, tests are failing

#9027 Added Scaled Exponential Linear Unit Activation Function
  neural_network/activation_functions/scaled_exponential_linear_unit.py
Labels: awaiting reviews

#8753 Added nth_sgonal_num.py
  maths/polygonal_numbers.py
Labels: awaiting reviews

#9020 Added an add at position subroutiune to linked list
  data_structures/linked_list/__init__.py
Labels: awaiting reviews

#9055 Euler 070 partial replacement of numpy loops.
  .github/workflows/project_euler.yml
  project_euler/problem_070/sol1.py
Labels: awaiting reviews

#8938 jacobi_iteration_method.py the use of vector operations, which reduces the calculation time by dozens of times
  arithmetic_analysis/jacobi_iteration_method.py
Labels: awaiting reviews

#9062 Delete empty junk file
  DIRECTORY.md
  arithmetic_analysis/junk.py
  computer_vision/haralick_descriptors.py
  conversions/convert_number_to_words.py
  graphs/tarjans_scc.py
Labels: enhancement, awaiting reviews, tests are failing

#9078 Update xgboost_regressor.py
  machine_learning/xgboost_regressor.py
Labels: awaiting reviews

#9076 Fix typos
  cellular_automata/langtons_ant.py
  compression/README.md
  hashes/README.md
  sorts/README.md
Labels: tests are failing

#9068 Rewrite of base32.py algorithm
  ciphers/base32.py
Labels: awaiting reviews

#9069 Rewrite of base85.py algorithm
  ciphers/base85.py
Labels: awaiting reviews

#9057 Add MFCC Feature Extraction Algorithm
  machine_learning/mfcc.py
Labels: awaiting reviews, require tests

#8714 Added Coulomb_Law
  physics/coulombs_law.py
Labels: awaiting reviews

#6602 feat(maths): add function to perform calculation
  maths/sum_of_two_positive_numbers_bitwise.py
Labels: awaiting reviews

#8996 Update k_means_clust.py
  machine_learning/k_means_clust.py
Labels: enhancement, awaiting reviews

#8603 Fix `mypy` errors in `erosion_operation.py`
  digital_image_processing/morphological_operations/erosion_operation.py
Labels: enhancement, awaiting reviews

#9083 Returning Index instead of boolean in knuth_morris_pratt (kmp) function, making it compatible with str.find().
  strings/knuth_morris_pratt.py
Labels: awaiting reviews

#9001 added smith waterman algorithm
  dynamic_programming/smith_waterman.py
Labels: awaiting reviews

#8906 Create word search algorithm
  DIRECTORY.md
  other/word_search.py
Labels: awaiting reviews
