Repository TheAlgorithms/Python, pull requests merged in 2023-10, with the labels that each got.

#9162 Fix mypy error in web_programming/reddit.py
  DIRECTORY.md
  web_programming/reddit.py
Labels: enhancement, awaiting reviews

#9165 Fix DeprecationWarning in local_weighted_learning.py
  machine_learning/local_weighted_learning/local_weighted_learning.py
Labels: enhancement, awaiting reviews

#9161 Fixed permute_recursive() by passing nums.copy(). Fixes #9014
  data_structures/arrays/permutations.py
Labels: enhancement, awaiting reviews

#9170 Fix DeprecationWarning in local_weighted_learning.py (Attempt 2)
  machine_learning/local_weighted_learning/local_weighted_learning.py
Labels: enhancement, awaiting reviews

#9178 Deleted sorts/random_pivot_quick_sort.py. Fixes #9124
  sorts/random_pivot_quick_sort.py
Labels: enhancement, awaiting reviews

#9182 Deleted sorts/random_normal_distribution_quicksort.py .Fixes #9124
  sorts/random_normal_distribution_quicksort.py
Labels: enhancement, awaiting reviews

#9180 Deleted add.py. As stated in #6216
  maths/add.py
Labels: enhancement, awaiting reviews

#9208 Made binary_tree_treaversals.py memory-friendly using generators based travels. Fixes #8725
  data_structures/binary_tree/binary_tree_traversals.py
Labels: enhancement, awaiting reviews

#9272 Fix ruff warning
  .github/workflows/ruff.yml
  DIRECTORY.md
Labels: enhancement

#9278 [NEW ALGORITHM] Rotate linked list by K.
  data_structures/linked_list/rotate_to_the_right.py
Labels: awaiting reviews

#9237 binary_search_traversals.py made memory-friendly using generators. Fixes #8725 completely.
  data_structures/binary_tree/binary_tree_traversals.py
Labels: enhancement, awaiting reviews

#9229 Euler072 - application of vector operations to reduce calculation time and refactoring numpy
  project_euler/problem_072/sol1.py
Labels: enhancement, awaiting reviews

#9325 Remove myself from CODEOWNERS
  .github/CODEOWNERS
  DIRECTORY.md
Labels: enhancement, awaiting reviews

#9323 add reverse k group linkedlist
  data_structures/linked_list/reverse_k_group.py
Labels: awaiting reviews

#9475 Add typing to binary_exponentiation_2.py
  maths/binary_exponentiation_2.py
Labels: enhancement, awaiting reviews

#9471 Add typing to binary_exponentiation.py
  maths/binary_exponentiation.py
Labels: enhancement, awaiting reviews

#9477 Add typing to binary_exponentiation_3.py
  maths/binary_exponentiation_3.py
Labels: enhancement, awaiting reviews

#9480 Add typng to binomial_coefficient.py
  maths/binomial_coefficient.py
Labels: enhancement, awaiting reviews

#9482 Deleted minmax.py. Fixes #8098
  backtracking/minmax.py
Labels: enhancement, awaiting reviews

#9228 Removed maths/miller_rabin.py , Double implementation. #8098
  maths/miller_rabin.py
Labels: enhancement, awaiting reviews

#9516 pre-commit autoupdate && pre-commit run --all-files
  .pre-commit-config.yaml
  DIRECTORY.md
Labels: enhancement, awaiting reviews

#9576 Upgrade to Python 3.12
  .github/workflows/build.yml
  .github/workflows/ruff.yml
  CONTRIBUTING.md
  DIRECTORY.md
  backtracking/combination_sum.py
  computer_vision/cnn_classification.py.DISABLED.txt
  dynamic_programming/k_means_clustering_tensorflow.py.DISABLED.txt
  fuzzy_logic/fuzzy_operations.py.DISABLED.txt
  machine_learning/lstm/lstm_prediction.py.DISABLED.txt
  maths/maclaurin_series.py
  quantum/bb84.py.DISABLED.txt
  quantum/deutsch_jozsa.py.DISABLED.txt
  quantum/half_adder.py.DISABLED.txt
  quantum/not_gate.py.DISABLED.txt
  quantum/q_full_adder.py.DISABLED.txt
  quantum/quantum_entanglement.py.DISABLED.txt
  quantum/quantum_teleportation.py.DISABLED.txt
  quantum/ripple_adder_classic.py.DISABLED.txt
  quantum/single_qubit_measure.py.DISABLED.txt
  quantum/superdense_coding.py.DISABLED.txt
  requirements.txt
Labels: awaiting reviews, tests are failing, documentation

#9581 Fix accuracy in maclaurin_series on Python 3.12
  maths/maclaurin_series.py
Labels: enhancement, awaiting reviews

#9580 Upgrade our Devcontainer to Python 3.12 on Debian bookworm
  .devcontainer/Dockerfile
  .devcontainer/README.md
  .devcontainer/devcontainer.json
Labels: enhancement, awaiting reviews

#9431 merge double_factorial
  maths/double_factorial.py
  maths/double_factorial_iterative.py
  maths/double_factorial_recursive.py
Labels: enhancement, awaiting reviews, require descriptive names

#9351 Update newtons_law_of_gravitation.py : Typo(Space Removed)
  physics/newtons_law_of_gravitation.py
Labels: enhancement, awaiting reviews

#9651 Add typing to stooge_sort.py
  sorts/stooge_sort.py
Labels: enhancement, awaiting reviews

#9652 Add typing to shell_sort.py
  sorts/shell_sort.py
Labels: enhancement, awaiting reviews

#9654 Add typing to selection_sort.py
  sorts/selection_sort.py
Labels: enhancement, awaiting reviews

#9426 Fixed file name in transposition_cipher_encrypt_decrypt_file.py. Fixing bug file not found.
  ciphers/prehistoric_men.txt
  ciphers/transposition_cipher_encrypt_decrypt_file.py
Labels: enhancement, awaiting reviews

#9667 Update coulombs_law.py docs
  physics/coulombs_law.py
Labels: enhancement, awaiting reviews

#9668 Add Comments
  data_structures/linked_list/circular_linked_list.py
  data_structures/linked_list/swap_nodes.py
Labels: enhancement, awaiting reviews, tests are failing

#9695 Arunsiva003 patch 1 flatten tree
  data_structures/binary_tree/flatten_binarytree_to_linkedlist.py
Labels: awaiting reviews

#9363 add median of matrix
  matrix/median_matrix.py
Labels: awaiting reviews

#9148 UPDATED rat_in_maze.py
  backtracking/rat_in_maze.py
Labels: enhancement, awaiting reviews

#9753 Moved relu.py from maths/ to neural_network/activation_functions
  DIRECTORY.md
  neural_network/activation_functions/rectified_linear_unit.py
Labels: enhancement, awaiting reviews

#9666 Added Photoelectric effect equation
  physics/photoelectric_effect.py
Labels: awaiting reviews

#9324 [New Algorithm] - Bell Numbers
  maths/bell_numbers.py
Labels: awaiting reviews

#9288 Palindromic
  dynamic_programming/longest_palindromic_subsequence.py
Labels: awaiting reviews

#9717 Added Mirror Formulae Equation
  DIRECTORY.md
  physics/mirror_formulae.py
Labels: tests are failing

#9775 Fletcher 16
  hashes/fletcher16.py
Labels: tests are failing

#9374 Added largest_pow_of_two_le_num
  bit_manipulation/largest_pow_of_two_le_num.py
Labels: awaiting reviews

#9712 Program to convert a given string to Pig Latin
  strings/pig_latin.py
Labels: awaiting reviews

#9794 Fermat_little_theorem type annotation
  maths/fermat_little_theorem.py
Labels: enhancement, awaiting reviews

#9800 Karatsuba type annotation
  maths/karatsuba.py
Labels: enhancement, awaiting reviews

#9799 hardy_ramanujanalgo type annotation
  maths/hardy_ramanujanalgo.py
Labels: enhancement, awaiting reviews

#9823 [bug fixing] Edge case of the double ended queue
  data_structures/queue/double_ended_queue.py
Labels: enhancement, awaiting reviews

#9824 Changing the directory of sigmoid_linear_unit.py
  neural_network/activation_functions/sigmoid_linear_unit.py
Labels: enhancement, awaiting reviews

#9825 largest divisible subset
  dynamic_programming/largest_divisible_subset.py
Labels: awaiting reviews

#9525 Updated check_bipartite_graph_dfs.py
  graphs/check_bipartite_graph_dfs.py
Labels: enhancement

#9851 Updated prime_numbers.py testcases.
  maths/prime_numbers.py
Labels: enhancement

#9875 print reverse: A LinkedList with a tail pointer
  DIRECTORY.md
  data_structures/linked_list/print_reverse.py
Labels: enhancement, awaiting reviews

#9727 camelCase to snake_case conversion - Fixes #9726
  strings/camel_case_to_snake_case.py
Labels: awaiting reviews

#9874 feat: :sparkles: calculating the resitance of resistor using color codes
  electronics/resistor_color_code.py
Labels: awaiting reviews

#9861 Match a pattern and String using backtracking
  backtracking/match_word_pattern.py
Labels: awaiting reviews

#9765 Added algorithm to deeply clone a graph
  graphs/deep_clone_graph.py
Labels: awaiting reviews

#9783 added laplacian_filter file
  digital_image_processing/filters/laplacian_filter.py
Labels: awaiting reviews

#9871 Symmetric tree
  data_structures/binary_tree/symmetric_tree.py
Labels: awaiting reviews, require tests

#9886 Use dataclasses in singly_linked_list.py
  DIRECTORY.md
  data_structures/linked_list/singly_linked_list.py
Labels: enhancement, awaiting reviews

#9866 Added Majority Voting Algorithm
  other/majority_vote_algorithm.py
Labels: awaiting reviews

#9769 Consolidate gamma
  maths/gamma.py
  maths/gamma_recursive.py
Labels: enhancement, awaiting reviews

#9942 Added Mish Activation Function
  neural_network/activation_functions/mish.py
Labels: awaiting reviews

#9945 Segmented sieve - doctests
  maths/segmented_sieve.py
Labels: enhancement

#9839 Mention square matrices in strassen docs and make it more clear
  divide_and_conquer/strassen_matrix_multiplication.py
Labels: enhancement, awaiting reviews

#9973 Create fractional_cover_problem.py
  greedy_methods/fractional_cover_problem.py
Labels: awaiting reviews

#10027 add : trapped water program under dynamic programming
  dynamic_programming/trapped_water.py
Labels: awaiting reviews

#10012 Add doctests, type hints; fix bug for dynamic_programming/minimum_partition.py
  dynamic_programming/minimum_partition.py
Labels: enhancement

#10084 Made Changes shifted CRT, modular division to maths directory
  maths/chinese_remainder_theorem.py
  maths/modular_division.py
Labels: enhancement, awaiting reviews

#9969 Created folder for losses in Machine_Learning
  machine_learning/loss_functions/binary_cross_entropy.py
  machine_learning/loss_functions/mean_squared_error.py
Labels: awaiting reviews

#9977 Added Squareplus Activation Function
  neural_network/activation_functions/squareplus.py
Labels: awaiting reviews

#10011 Create strip.py
  strings/strip.py
Labels: awaiting reviews

#10114 add : Best time to buy and sell stock program under GREEDY methods
  greedy_methods/best_time_to_buy_and_sell_stock.py
Labels: awaiting reviews

#10051 In place of calculating the factorial several times we can run a loop k times to calculate the combination
  maths/combinations.py
Labels: enhancement, awaiting reviews

#9505 Power of 4
  bit_manipulation/power_of_4.py
Labels: awaiting reviews

#9864 Added Median of Medians Algorithm
  searches/median_of_medians.py
Labels: awaiting reviews

#9656 Rename maths/binary_exponentiation_3.py
  DIRECTORY.md
  maths/binary_exponentiation_2.py
Labels: enhancement, awaiting reviews

#9856 equilibrium index in an array
  data_structures/arrays/equilibrium_index_in_array.py
Labels: awaiting reviews

#10140 Consolidated two scripts reverse_letters.py and reverse_long_words.py into one
  DIRECTORY.md
  strings/reverse_letters.py
  strings/reverse_long_words.py
Labels: enhancement, awaiting reviews

#10120 Added Germain primes algorithm to the maths folder
  maths/germain_primes.py
Labels: awaiting reviews

#10043 Add Soboleva Modified Hyberbolic Tangent function
  neural_network/activation_functions/soboleva_modified_hyperbolic_tangent.py
Labels: awaiting reviews

#10030 Add binary step activation function
  neural_network/activation_functions/binary_step.py
Labels: awaiting reviews

#10081 Add DocTests to is_palindrome.py
  data_structures/linked_list/is_palindrome.py
Labels: enhancement

#10135 Add DocTests to magicdiamondpattern.py
  other/magicdiamondpattern.py
Labels: enhancement, awaiting reviews

#10141 Added Huber Loss Function
  machine_learning/loss_functions/huber_loss.py
Labels: awaiting reviews

#10156 Add DocTests to diffie.py
  ciphers/diffie.py
Labels: enhancement

#10161 test_digital_image_processing -> test_local_binary_pattern replacing a large image with a smaller one
  digital_image_processing/test_digital_image_processing.py
Labels: enhancement

#10169 Remove backslashes from is_palindrome.py
  data_structures/linked_list/is_palindrome.py
Labels: enhancement, awaiting reviews

#9163 Added ciphers/permutation_cipher.py.
  ciphers/permutation_cipher.py
Labels: awaiting reviews

#10144 Added the Chebyshev distance function
  maths/chebyshev_distance.py
Labels: awaiting reviews

#10143 Added the Minkowski distance function
  maths/minkowski_distance.py
Labels: awaiting reviews

#10188 backtracking -> word_search - replacing the example in doctest
  backtracking/word_search.py
Labels: enhancement, awaiting reviews

#9250 TypeError for non-integer input
  maths/number_of_digits.py
Labels: enhancement, awaiting reviews

#9687 seperation between description and docstrings
  maths/factorial.py
Labels: awaiting reviews

#9913 Added the algorithm to compute Reynolds number in the physics section
  physics/reynolds_number.py
Labels: awaiting reviews

#10121 Fixes #9943 Added Doctests to binary_exponentiation_3.py
  DIRECTORY.md
  maths/binary_exponentiation_2.py
Labels: enhancement, awaiting reviews

#10152 Added categorical_crossentropy loss function
  machine_learning/loss_functions/categorical_cross_entropy.py
Labels: awaiting reviews

#10221 Gaussian_elemination - change to remove warning
  arithmetic_analysis/gaussian_elimination.py
Labels: enhancement, awaiting reviews

#10095 Add tests for infix_2_postfix() in infix_to_prefix_conversion.py
  data_structures/stacks/infix_to_prefix_conversion.py
Labels: enhancement

#10038 carmichael_number - add doctests
  maths/carmichael_number.py
Labels: enhancement, awaiting reviews

#10244 k_means_clust - change to remove warning
  machine_learning/k_means_clust.py
Labels: enhancement, awaiting reviews

#10242 Add doctests to primelib.py
  maths/primelib.py
Labels: enhancement, awaiting reviews

#10259 Fix bug and edit doctests for infix_to_prefix_conversion
  data_structures/stacks/infix_to_prefix_conversion.py
Labels: tests are failing

#10251 Improve primelib.py test coverage #9943
  maths/primelib.py
Labels: enhancement, awaiting reviews

#10269 Adding doctests in simpson_rule.py
  maths/simpson_rule.py
Labels: enhancement

#10281 Add Ruff rules for pandas-vet and pytest-style
  .pre-commit-config.yaml
  DIRECTORY.md
  blockchain/diophantine_equation.py
  ciphers/xor_cipher.py
  conversions/decimal_to_hexadecimal.py
  data_structures/binary_tree/binary_search_tree_recursive.py
  data_structures/hashing/tests/test_hash_map.py
  data_structures/linked_list/circular_linked_list.py
  digital_image_processing/test_digital_image_processing.py
  graphs/graph_adjacency_list.py
  graphs/graph_adjacency_matrix.py
  hashes/sha256.py
  knapsack/tests/test_greedy_knapsack.py
  knapsack/tests/test_knapsack.py
  linear_algebra/src/lib.py
  linear_algebra/src/schur_complement.py
  linear_algebra/src/test_linear_algebra.py
  machine_learning/dimensionality_reduction.py
  machine_learning/k_means_clust.py
  maths/least_common_multiple.py
  maths/modular_division.py
  maths/prime_check.py
  matrix/sherman_morrison.py
  matrix/tests/test_matrix_operation.py
  project_euler/problem_054/test_poker_hand.py
  pyproject.toml
  strings/knuth_morris_pratt.py
  strings/rabin_karp.py
Labels: enhancement, awaiting reviews

#10210 Add doctests to carmichael_number.py
  maths/carmichael_number.py
Labels: awaiting reviews

#10282 Count pairs with given sum
  data_structures/arrays/pairs_with_given_sum.py
Labels: awaiting reviews

#9849 Added imply gate to boolean algebra
  boolean_algebra/imply_gate.py
Labels: awaiting reviews

#10040 add find triplets with 0 sum (3sum)
  data_structures/arrays/find_triplets_with_0_sum.py
Labels: awaiting reviews

#10344 Added nimply gate to boolean_algebra
  boolean_algebra/nimply_gate.py
Labels: awaiting reviews

#10159 Add Damerau-Levenshtein distance algorithm
  strings/damerau_levenshtein_distance.py
Labels: awaiting reviews

#10369 Modified comments on lower.py
  strings/lower.py
Labels: enhancement, awaiting reviews

#10033 added doctests for dynamicprogramming/minimum_partition
  dynamic_programming/integer_partition.py
  dynamic_programming/minimum_partition.py
Labels: enhancement, awaiting reviews

#10401 Expand euler phi function doctest
  maths/basic_maths.py
Labels: enhancement, awaiting reviews

#10229 Adding avg and mps speed formulae for ideal gases
  physics/speeds_of_gas_molecules.py
Labels: awaiting reviews

#9978 Updated test cases of power_sum.py
  backtracking/power_sum.py
Labels: enhancement, awaiting reviews

#10422 Remove doctest in `xgboost_regressor.py` main function
  machine_learning/xgboost_regressor.py
Labels: enhancement

#9881 Added validate sudoku board function
  matrix/validate_sudoku_board.py
Labels: awaiting reviews

#10445 Performance: 80% faster Project Euler 145
  project_euler/problem_145/sol1.py
Labels: enhancement

#10442 Updated Comments on upper.py
  strings/upper.py
Labels: enhancement

#10467 Disable unused dependencies
  requirements.txt
Labels: enhancement

#10361 fix: incorrect range detection in find_missing_number
  bit_manipulation/missing_number.py
Labels: enhancement, awaiting reviews

#10438 added rkf45 method
  maths/rkf45.py
Labels: awaiting reviews

#10503 Performance: 75% faster Project Euler 187
  project_euler/problem_187/sol1.py
Labels: enhancement

#10482 [Add] : Job Sequence program under GREEDY methods
  scheduling/job_sequence_with_deadline.py
Labels: awaiting reviews

#10516 Fix typo in filename: ciphers/trifid_cipher.py
  DIRECTORY.md
  ciphers/trifid_cipher.py
Labels: enhancement, awaiting reviews

#10469 Omit `project_euler/` from coverage reports
  pyproject.toml
Labels: enhancement

#10546 validate_solutions.py: os.getenv('GITHUB_TOKEN', '')
  DIRECTORY.md
  scripts/validate_solutions.py
Labels: enhancement, awaiting reviews

#10479 updated physics/archimedes_principle.py
  physics/archimedes_principle.py
  physics/archimedes_principle_of_buoyant_force.py
Labels: enhancement

#10552 Revert "validate_solutions.py: os.getenv('GITHUB_TOKEN', '')"
  DIRECTORY.md
  scripts/validate_solutions.py
Labels: enhancement, awaiting reviews

#10191 Changes the code To return the list in dynamic_programming/subset_generation.py
  dynamic_programming/subset_generation.py
Labels: enhancement

#10397 test: adding more tests to a star algorithm
  graphs/a_star.py
Labels: awaiting reviews

#10562 Dynamic programming/matrix chain multiplication
  DIRECTORY.md
  dynamic_programming/matrix_chain_multiplication.py
Labels: require tests, require descriptive names

#10424 Fix numpy deprecation warning in `2_hidden_layers_neural_network.py`
  neural_network/2_hidden_layers_neural_network.py
Labels: enhancement

#10418 Move and rename `maths/greedy_coin_change.py`
  greedy_methods/minimum_coin_change.py
Labels: enhancement

#10142 Add note to feature_request.yml about not opening issues for new algorithms
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: enhancement

#10565 Delete `texttable` from dependencies
  requirements.txt
Labels: enhancement

#10015 add tests for tree_sort
  sorts/tree_sort.py
Labels: enhancement

#9628 Update volume.py with volume of Icosahedron
  maths/volume.py
Labels: enhancement, awaiting reviews

#10572 Converted tests into doctests
  boolean_algebra/and_gate.py
  boolean_algebra/imply_gate.py
  boolean_algebra/nand_gate.py
  boolean_algebra/nimply_gate.py
  boolean_algebra/not_gate.py
  boolean_algebra/or_gate.py
  boolean_algebra/xnor_gate.py
  boolean_algebra/xor_gate.py
Labels: enhancement, awaiting reviews

#9231 Refactoring and optimization of the lu_decomposition algorithm
  arithmetic_analysis/lu_decomposition.py
Labels: enhancement, awaiting reviews

#10073 Delete dynamic_programming/longest_sub_array.py
  dynamic_programming/longest_sub_array.py
Labels: enhancement, awaiting reviews

#10094 Adds Doc test in depth_first_search_2.py
  graphs/depth_first_search_2.py
Labels: enhancement, awaiting reviews

#9976 Minimization of while loop in Armstrong Numbers
  maths/armstrong_numbers.py
Labels: enhancement, awaiting reviews

#10599 Rename binary_tree_traversals.md to README.md
  DIRECTORY.md
  data_structures/binary_tree/README.md
Labels: awaiting reviews, documentation

#10432 Floor and ceil in Binary search tree added
  data_structures/binary_tree/floor_and_ceiling.py
Labels: require tests

#9975 update segmenttree docstrings Fixes #9943
  data_structures/binary_tree/segment_tree.py
Labels: enhancement

#10629 Added test cases to join.py
  strings/join.py
Labels: enhancement, awaiting reviews

#10533 Hacktoberfest: Added Octal Number to Hexadecimal Number Conversion Algorithm
  conversions/octal_to_hexadecimal.py
Labels: awaiting reviews

#10045 Add matrix_multiplication
  matrix/matrix_multiplication_recursion.py
Labels: awaiting reviews
