Repository TheAlgorithms/Python, pull requests merged in 2023-06, with the labels that each got.

#8773 Create a Simultaneous Equation Solver Algorithm
  .vscode/settings.json
  maths/simultaneous_linear_equation_solver.py
Labels: awaiting reviews, require tests, require type hints

#8738 Pytest locally fails due to API_KEY env variable
  web_programming/currency_converter.py
Labels: enhancement, awaiting reviews

#8808 Create number container system algorithm
  DIRECTORY.md
  other/number_container_system.py
Labels: awaiting reviews

#8626 Improve readability of ciphers/mixed_keyword_cypher.py
  ciphers/mixed_keyword_cypher.py
Labels: enhancement, awaiting reviews

#8813 Create count negative numbers in matrix algorithm
  DIRECTORY.md
  matrix/count_negative_numbers_in_sorted_matrix.py
Labels: awaiting reviews, require tests

#8752 Fix removing the root node in binary_search_tree.py removes the whole tree
  data_structures/binary_tree/binary_search_tree.py
Labels: enhancement, awaiting reviews

#6025 Added apr_interest function to financial
  financial/interest.py
Labels: enhancement, awaiting reviews

#8802 Dijkstra algorithm with binary grid
  .pre-commit-config.yaml
  data_structures/queue/double_ended_queue.py
  graphs/dijkstra_binary_grid.py
  maths/least_common_multiple.py
  project_euler/problem_054/sol1.py
  pyproject.toml
Labels: awaiting reviews

#8786 Fix `mypy` errors in `maths/sigmoid_linear_unit.py`
  maths/sigmoid_linear_unit.py
Labels: enhancement, awaiting reviews

#8801 Energy conversions
  conversions/energy_conversions.py
Labels: tests are failing

#8761 Algorithm: Calculating Product Sum from a Special Array with Nested Structures
  DIRECTORY.md
  data_structures/arrays/product_sum.py
Labels: awaiting reviews

#8837 GitHub Actions build: Add more tests
  .github/workflows/build.yml
  DIRECTORY.md
Labels: awaiting reviews

#8838 Fix failing pytest quantum/bb84.py
  .github/workflows/build.yml
  quantum/bb84.py
Labels: awaiting reviews

#8832 Add power sum problem
  backtracking/power_sum.py
Labels: awaiting reviews

#8836 Remove duplicate implementation of Collatz sequence
  DIRECTORY.md
  maths/3n_plus_1.py
  maths/collatz_sequence.py
Labels: awaiting changes
