Repository TheAlgorithms/Python, pull requests merged in 2024-10, with the labels that each got.

#11621 Drop six from our GitHub Actions
  .github/workflows/build.yml
Labels: enhancement, dependencies

#11590 Add word ladder algorithm in backtracking
  DIRECTORY.md
  backtracking/word_ladder.py
Labels: awaiting reviews

#11619 Improve comments, add doctests in symmetric_tree.py
  data_structures/binary_tree/symmetric_tree.py
Labels: enhancement, awaiting reviews

#11690 Adding Doctests to floyd_warshall.py
  dynamic_programming/floyd_warshall.py
Labels: enhancement, awaiting reviews

#11687 Add Word Break algorithm
  backtracking/word_break.py
Labels: awaiting reviews

#11685 Improve comments, docstrings in next_greatest_element.py
  data_structures/stacks/next_greater_element.py
Labels: enhancement, awaiting reviews

#11668 Improve comments, add doctests for kahns_algorithm_topo.py
  graphs/kahns_algorithm_topo.py
Labels: enhancement, awaiting reviews

#11721 Added doctests to min_cost_string_conversion.py and removed :c specifier
  strings/min_cost_string_conversion.py
Labels: awaiting reviews

#11747 feat: Implemented Matrix Exponentiation Method
  maths/fibonacci.py
Labels: enhancement, awaiting reviews

#11674 Added new algorithm to generate numbers in lexicographical order
  data_structures/stacks/lexicographical_numbers.py
Labels: awaiting reviews

#11777 feat: add testcases for longest_common_subsequence
  dynamic_programming/longest_common_subsequence.py
Labels: enhancement, awaiting reviews

#11772 Update ruff usage example in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: awaiting reviews, documentation

#11666 Implemented Exponential Search with binary search for improved perfor…
  searches/exponential_search.py
Labels: awaiting reviews

#11811 feat: add testcase of polynom_for_points
  linear_algebra/src/polynom_for_points.py
Labels: enhancement, awaiting reviews

#11835 added gronsfeld cipher implementation
  ciphers/gronsfeld_cipher.py
Labels: awaiting reviews

#11881 feat: add test cases in cipher's autokey
  ciphers/autokey.py
Labels: enhancement, awaiting reviews
