Repository TheAlgorithms/Python, pull requests merged in 2024-01, with the labels that each got.

#11234 fix: consider months and days in `years_old`
  .github/workflows/build.yml
  web_programming/get_top_billionaires.py
Labels: enhancement, awaiting reviews

#11233 fix: use `GITHUB_ACTOR` in `git config`
  .github/workflows/directory_writer.yml
Labels: enhancement, awaiting reviews

#11236 chore: update `actions/setup-python` to `v5`
  .github/workflows/directory_writer.yml
  .github/workflows/project_euler.yml
Labels: enhancement

#11237 style: use proper indentation in `ruff.yml`
  .github/workflows/build.yml
  .github/workflows/ruff.yml
  .pre-commit-config.yaml
Labels: enhancement, awaiting reviews

#11147 Added doctest to skew_heap.py
  data_structures/heap/skew_heap.py
Labels: awaiting reviews
