Repository TheAlgorithms/Python, pull requests merged in 2024-04, with the labels that each got.

#11337 Enable ruff RUF100 rule
  audio_filters/butterworth_filter.py
  data_structures/binary_tree/basic_binary_tree.py
  data_structures/binary_tree/non_recursive_segment_tree.py
  data_structures/binary_tree/red_black_tree.py
  data_structures/binary_tree/segment_tree.py
  data_structures/heap/min_heap.py
  dynamic_programming/longest_common_subsequence.py
  dynamic_programming/longest_increasing_subsequence_o_nlogn.py
  graphs/articulation_points.py
  graphs/dinic.py
  other/sdes.py
  project_euler/problem_011/sol2.py
  pyproject.toml
  strings/manacher.py
Labels: enhancement

#11341 Enable ruff SIM102 rule
  data_structures/arrays/sudoku_solver.py
  data_structures/stacks/balanced_parentheses.py
  graphs/a_star.py
  graphs/bi_directional_dijkstra.py
  other/davis_putnam_logemann_loveland.py
  project_euler/problem_033/sol1.py
  project_euler/problem_037/sol1.py
  project_euler/problem_107/sol1.py
  project_euler/problem_207/sol1.py
  pyproject.toml
  scheduling/shortest_job_first.py
  scripts/validate_solutions.py
  web_programming/emails_from_url.py
Labels: awaiting reviews

#11346 Enable ruff INP001 rule
  data_structures/arrays/__init__.py
  data_structures/hashing/tests/__init__.py
  digital_image_processing/morphological_operations/__init__.py
  electronics/__init__.py
  electronics/circular_convolution.py
  fractals/__init__.py
  geometry/__init__.py
  greedy_methods/__init__.py
  linear_algebra/src/gaussian_elimination_pivoting/__init__.py
  linear_programming/__init__.py
  maths/numerical_analysis/__init__.py
  maths/special_numbers/__init__.py
  neural_network/activation_functions/__init__.py
  neural_network/activation_functions/mish.py
  pyproject.toml
Labels: enhancement

#11344 Enable ruff RUF005 rule
  data_structures/binary_tree/binary_search_tree.py
  dynamic_programming/subset_generation.py
  maths/odd_sieve.py
  pyproject.toml
Labels: enhancement

#11345 Enable ruff PGH003 rule
  compression/huffman.py
  data_structures/binary_tree/binary_search_tree.py
  data_structures/linked_list/rotate_to_the_right.py
  fractals/mandelbrot.py
  graphics/bezier_curve.py
  maths/entropy.py
  matrix/spiral_print.py
  matrix/tests/test_matrix_operation.py
  project_euler/problem_092/sol1.py
  project_euler/problem_104/sol1.py
  pyproject.toml
  scripts/validate_filenames.py
  scripts/validate_solutions.py
  web_programming/covid_stats_via_xpath.py
Labels: enhancement, awaiting reviews

#11350 Do not fix ruff EXE001 rule
  pyproject.toml
Labels: enhancement

#11374 Add doctests in all functions in basic_string.py
  genetic_algorithm/basic_string.py
Labels: awaiting reviews

#11349 Enable ruff RUF007 rule
  data_structures/linked_list/skip_list.py
  pyproject.toml
  sorts/bead_sort.py
Labels: enhancement, awaiting reviews

#11378 Enable ruff RUF001 rule
  fuzzy_logic/fuzzy_operations.py
  physics/basic_orbital_capture.py
  physics/malus_law.py
  pyproject.toml
Labels: enhancement

#11383 Fix ARG005 per file ignore
  machine_learning/linear_discriminant_analysis.py
  pyproject.toml
Labels: enhancement, awaiting reviews

#11388 Enable ruff UP031 rule
  data_structures/arrays/sudoku_solver.py
  neural_network/input_data.py
Labels: awaiting reviews
