Repository TheAlgorithms/Python, pull requests merged in 2024-06, with the labels that each got.

#11420 Remove duplicate implementation of median of two arrays algorithm
  DIRECTORY.md
  maths/median_of_two_arrays.py
Labels: enhancement, awaiting reviews

#10252 Fixes #9943
  backtracking/all_permutations.py
  backtracking/all_subsequences.py
Labels: awaiting reviews

#11238 Add KL divergence loss algorithm
  machine_learning/loss_functions.py
Labels: awaiting reviews

#11432 Add rainfall intensity calculation function
  physics/rainfall_intensity.py
Labels: awaiting reviews

#11381 Remove some per file ignores
  DIRECTORY.md
  pyproject.toml
Labels: enhancement

#11467 chore: fix typos
  computer_vision/haralick_descriptors.py
  graphs/strongly_connected_components.py
  maths/points_are_collinear_3d.py
  neural_network/convolution_neural_network.py
Labels: awaiting reviews
