Repository TheAlgorithms/Python, pull requests merged in 2024-12, with the labels that each got.

#12462 Fix sphinx/build_docs warnings for geodesy
  geodesy/haversine_distance.py
Labels: enhancement, awaiting reviews

#12467 Fix sphinx/build_docs warnings for physics/horizontal_projectile_motion
  physics/horizontal_projectile_motion.py
Labels: enhancement, awaiting reviews

#12469 Fix sphinx/build_docs warnings for graphs/check_bipatrite
  graphs/check_bipatrite.py
Labels: awaiting reviews

#12470 Fix sphinx/build_docs warnings for data_structures/binary_tree/mirror_binary_tree
  data_structures/binary_tree/mirror_binary_tree.py
Labels: enhancement, awaiting reviews

#12353 Added test to linear regression #9943
  machine_learning/linear_regression.py
Labels: enhancement, awaiting reviews

#12387 adding test to electronics/electric_power.py #9943
  electronics/electric_power.py
Labels: awaiting reviews, tests are failing

#12477 Add additional doctests, fix grammatical errors for maths/perfect_number.py
  maths/perfect_number.py
Labels: awaiting reviews

#12383 Remove inaccessible URL in computer_vision/README.md
  computer_vision/README.md
Labels: awaiting reviews, documentation

#12193 adding doctests to maths/trapezoidal_rule.py
  maths/trapezoidal_rule.py
Labels: enhancement, awaiting reviews

#12448 compare-method added to Vector class in lib.py
  linear_algebra/src/lib.py
Labels: awaiting reviews

#12480 Fix sphinx/build_docs warnings for physics/newtons_second_law_of_motion
  physics/newtons_second_law_of_motion.py
Labels: awaiting reviews

#12481 Fix sphinx/build_docs warnings for maths/zellers_congruence
  maths/zellers_congruence.py
Labels: enhancement, awaiting reviews

#12483 Fix sphinx/build_docs warnings for linear_algebra
  linear_algebra/gaussian_elimination.py
  linear_algebra/lu_decomposition.py
  linear_algebra/src/gaussian_elimination_pivoting.py
  linear_algebra/src/rank_of_matrix.py
  linear_algebra/src/schur_complement.py
  linear_algebra/src/transformations_2d.py
Labels: enhancement, awaiting reviews

#12390 current_stock_price test added #9943
  web_programming/current_stock_price.py
Labels: awaiting reviews, tests are failing

#12484 Fix sphinx/build_docs warnings for dynamic_programming
  dynamic_programming/all_construct.py
  dynamic_programming/combination_sum_iv.py
  dynamic_programming/fizz_buzz.py
  dynamic_programming/knapsack.py
  dynamic_programming/longest_common_substring.py
  dynamic_programming/longest_increasing_subsequence.py
  dynamic_programming/matrix_chain_multiplication.py
  dynamic_programming/max_product_subarray.py
  dynamic_programming/minimum_squares_to_represent_a_number.py
  dynamic_programming/regex_match.py
  dynamic_programming/rod_cutting.py
  dynamic_programming/subset_generation.py
  dynamic_programming/viterbi.py
Labels: awaiting reviews

#12437 Tests electronics/electric_conductivity.py #9943
  DIRECTORY.md
  conversions/rectangular_to_polar.py
  electronics/electric_conductivity.py
Labels: awaiting reviews

#12368 Implemented doctests for geometry-related classes
  data_structures/arrays/sudoku_solver.py
  geometry/geometry.py
Labels: awaiting reviews

#12354 #9943 : Adding coverage test for basic_graphs.py
  graphs/basic_graphs.py
Labels: enhancement, awaiting reviews

#12073 Contributes to #9943 by adding tests to monotonic_array.py
  data_structures/arrays/monotonic_array.py
Labels: enhancement

#11779 Add doctest for quick_sort_3_partition. Contributes to #9943
  sorts/quick_sort_3_partition.py
Labels: enhancement

#9949 add some documentation for heap sort
  sorts/heap_sort.py
Labels: enhancement, awaiting reviews

#10265 Added the algorithm to compute the time period of a simple pendulum
  physics/period_of_pendulum.py
Labels: awaiting reviews

#11640 chore: improve comments and add tests to trapezoidal rule
  DIRECTORY.md
  maths/trapezoidal_rule.py
Labels: enhancement, awaiting reviews

#10929 Create digital differential analyzer_line.py
  graphics/digital_differential_analyzer_line.py
Labels: awaiting reviews

#10421 [ADDED] Implementation of Geometric Mean.
  maths/geometric_mean.py
Labels: awaiting reviews
