Repository TheAlgorithms/Python, pull requests merged in 2024-03, with the labels that each got.

#11224 adding a proper fractions algorithm
  .github/workflows/ruff.yml
  maths/numerical_analysis/proper_fractions.py
Labels: awaiting reviews

#11326 Enable ruff DTZ001 rule
  DIRECTORY.md
  other/gauss_easter.py
  pyproject.toml
Labels: awaiting reviews

#11331 Enable ruff N999 rule
  DIRECTORY.md
  dynamic_programming/longest_increasing_subsequence_o_nlogn.py
  graphs/directed_and_undirected_weighted_graph.py
  neural_network/two_hidden_layers_neural_network.py
  pyproject.toml
Labels: enhancement

#11330 Enable ruff PLW0120 rule
  pyproject.toml
  searches/fibonacci_search.py
  searches/ternary_search.py
Labels: enhancement, awaiting reviews

#11329 Enable ruff ICN001 rule
  ciphers/hill_cipher.py
  fractals/julia_sets.py
  fractals/koch_snowflake.py
  graphics/bezier_curve.py
  machine_learning/gradient_descent.py
  neural_network/input_data.py
  neural_network/two_hidden_layers_neural_network.py
  pyproject.toml
Labels: enhancement
