Repository TheAlgorithms/Python, pull requests merged in 2025-01, with the labels that each got.

#12515 Fix ruff
  DIRECTORY.md
  ciphers/base64_cipher.py
  project_euler/problem_002/sol4.py
  strings/wave_string.py
Labels: awaiting reviews, tests are failing

#12517 Fix #12510
  dynamic_programming/longest_increasing_subsequence.py
Labels: tests are failing

#12506 doctest all_combinations.py
  backtracking/all_combinations.py
Labels: enhancement, awaiting reviews

#12493 Add butterfly pattern implementation #12151
  graphics/butterfly_pattern.py
Labels: require descriptive names

#12396 Doomsday Algorithm: Fix leap year check
  other/doomsday.py
Labels: awaiting changes

#12530 Sphinx runs on ubuntu 24.04 arm
  .github/workflows/sphinx.yml
  DIRECTORY.md
Labels: enhancement, awaiting reviews, optimization

#11797 Update docstrings in the functions definitions.
  data_structures/arrays/sudoku_solver.py
Labels: enhancement, awaiting reviews
