Repository TheAlgorithms/Python, pull requests merged in 2025-08, with the labels that each got.

#12782 Codex/find and fix a bug
  maths/radix2_fft.py
Labels: awaiting reviews

#12771 Add new solution for the euler project problem 9
  DIRECTORY.md
  project_euler/problem_009/sol4.py
Labels: require descriptive names

#9295 Enhancement of the knapsack algorithm with memorization and generalisation
  knapsack/README.md
  knapsack/knapsack.py
  knapsack/tests/test_knapsack.py
Labels: documentation

#9317 added coordinate_compression
  DIRECTORY.md
  data_compression/coordinate_compression.py
Labels: awaiting reviews

#9630 Improve blockchain/README.md
  blockchain/README.md
Labels: tests are failing, documentation

#9935 Algorithm to find unique prime factors
  maths/prime_factors.py
Labels: enhancement

#10193 Combination sum fix and test cases
  backtracking/combination_sum.py
Labels: enhancement, awaiting reviews

#12877 Weierstrass Method
  maths/numerical_analysis/weierstrass_method.py
Labels: awaiting reviews

#10540 Fixing stock_span_problem.py
  DIRECTORY.md
  data_structures/stacks/stock_span_problem.py
Labels: enhancement

#11605 Add new test for bucket sort algorithm in sorts/bucket_sort.py
  sorts/bucket_sort.py
Labels: enhancement, awaiting reviews, tests are failing

#11749 Specify space complexity for merge sort
  sorts/merge_sort.py
Labels: enhancement, awaiting reviews

#11833 Add unit tests to binary_tree_path_sum.py
  data_structures/binary_tree/binary_tree_path_sum.py
Labels: enhancement

#12372 Adding a 3D plot to the k-means clustering algorithm
  machine_learning/k_means_clust.py
Labels: enhancement
