Repository TheAlgorithms/Python, pull requests merged in 2025-05, with the labels that each got.

#12717 Update and_gate
  boolean_algebra/and_gate.py
Labels: enhancement

#12705 Update longest_common_substring.py
  dynamic_programming/longest_common_substring.py
Labels: tests are failing

#12730 Delete empty source directory
  source/__init__.py
Labels: enhancement

#12731 Add PEP723 header to scripts/validate_solutions.py
  scripts/validate_solutions.py
Labels: enhancement, awaiting reviews

#12733 Add a proper shebang line to scripts/validate_filenames.py
  scripts/validate_filenames.py
Labels: enhancement, awaiting reviews

#12744 Lukazlim: Replace dependency `requests` with `httpx`
  DIRECTORY.md
  machine_learning/linear_regression.py
  physics/speeds_of_gas_molecules.py
  pyproject.toml
  requirements.txt
  scripts/validate_solutions.py
  uv.lock
  web_programming/co2_emission.py
  web_programming/covid_stats_via_xpath.py
  web_programming/crawl_google_results.py
  web_programming/crawl_google_scholar_citation.py
  web_programming/currency_converter.py
  web_programming/current_stock_price.py
  web_programming/current_weather.py
  web_programming/daily_horoscope.py
  web_programming/download_images_from_google_query.py
  web_programming/emails_from_url.py
  web_programming/fetch_anime_and_play.py
  web_programming/fetch_bbc_news.py
  web_programming/fetch_github_info.py
  web_programming/fetch_jobs.py
  web_programming/fetch_quotes.py
  web_programming/get_amazon_product_data.py
  web_programming/get_imdb_top_250_movies_csv.py
  web_programming/get_ip_geolocation.py
  web_programming/get_top_billionaires.py
  web_programming/get_top_hn_posts.py
  web_programming/giphy.py
  web_programming/instagram_crawler.py
  web_programming/instagram_pic.py
  web_programming/instagram_video.py
  web_programming/nasa_data.py
  web_programming/open_google_results.py
  web_programming/random_anime_character.py
  web_programming/recaptcha_verification.py
  web_programming/reddit.py
  web_programming/search_books_by_isbn.py
  web_programming/slack_message.py
  web_programming/test_fetch_github_info.py
  web_programming/world_covid19_stats.py
Labels: awaiting reviews

#12649 Add bidirectional search algorithm implementation
  graphs/bidirectional_search.py
Labels: require tests

#12772 maths/radix2_fft.py: Fix calculation for Python 3.14
  .github/workflows/directory_writer.yml
  maths/radix2_fft.py
Labels: awaiting reviews
