Repository TheAlgorithms/Python, pull requests merged in 2025-07, with the labels that each got.

#12815 Add unit tests for factorial.py
  maths/test_factorial.py
  web_programming/current_stock_price.py
Labels: awaiting reviews, tests are failing

#12821 Various ruff fixes
  DIRECTORY.md
  ciphers/hill_cipher.py
  data_structures/binary_tree/non_recursive_segment_tree.py
  data_structures/hashing/hash_map.py
  data_structures/heap/heap.py
  data_structures/heap/randomized_heap.py
  data_structures/heap/skew_heap.py
  data_structures/linked_list/skip_list.py
  data_structures/queues/queue_by_list.py
  data_structures/queues/queue_by_two_stacks.py
  data_structures/stacks/stack.py
  data_structures/stacks/stack_with_doubly_linked_list.py
  data_structures/stacks/stack_with_singly_linked_list.py
  graphs/graph_adjacency_list.py
  graphs/graph_adjacency_matrix.py
  graphs/graph_list.py
  graphs/minimum_spanning_tree_kruskal2.py
  graphs/minimum_spanning_tree_prims2.py
  matrix/matrix_class.py
  other/least_recently_used.py
  other/lfu_cache.py
  other/lru_cache.py
  pyproject.toml
  sorts/insertion_sort.py
  sorts/tim_sort.py
Labels: awaiting reviews

#12837 Fix devcontainer build failure
  .devcontainer/Dockerfile
  .devcontainer/README.md
  .devcontainer/devcontainer.json
  .devcontainer/post_install
  .github/workflows/devcontainer_ci.yml
Labels: invalid, awaiting reviews

#12841 Update .pre-commit-config.yaml to reflect current linting and formatt…
  .pre-commit-config.yaml
  web_programming/fetch_well_rx_price.py
Labels: awaiting reviews
